/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.12.5-snapshot-c2987628087f on Thu Sep  1 02:20:43 2011
 *
 * Copyright (c) 2011 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of QScintilla.
 * 
 * This file may be used under the terms of the GNU General Public
 * License versions 2.0 or 3.0 as published by the Free Software
 * Foundation and appearing in the files LICENSE.GPL2 and LICENSE.GPL3
 * included in the packaging of this file.  Alternatively you may (at
 * your option) use any later version of the GNU General Public
 * License if such license has been publicly approved by Riverbank
 * Computing Limited (or its successors, if any) and the KDE Free Qt
 * Foundation. In addition, as a special exception, Riverbank gives you
 * certain additional rights. These rights are described in the Riverbank
 * GPL Exception version 1.1, which can be found in the file
 * GPL_EXCEPTION.txt in this package.
 * 
 * Please review the following information to ensure GNU General
 * Public Licensing requirements will be met:
 * http://trolltech.com/products/qt/licenses/licensing/opensource/. If
 * you are unsure which license is appropriate for your use, please
 * review the following information:
 * http://trolltech.com/products/qt/licenses/licensing/licensingoverview
 * or contact the sales department at sales@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQsci.h"

#line 34 "sip/qscilexerfortran77.sip"
#include <Qsci/qscilexerfortran77.h>
#line 39 "./sipQsciQsciLexerFortran77.cpp"

#line 39 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qobject.sip"
#include <qobject.h>
#line 43 "./sipQsciQsciLexerFortran77.cpp"
#line 36 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qsettings.sip"
#include <qsettings.h>
#line 46 "./sipQsciQsciLexerFortran77.cpp"
#line 41 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qstring.sip"
#include <qstring.h>
#line 49 "./sipQsciQsciLexerFortran77.cpp"
#line 40 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtGui/qcolor.sip"
#include <qcolor.h>
#line 52 "./sipQsciQsciLexerFortran77.cpp"
#line 40 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtGui/qfont.sip"
#include <qfont.h>
#line 55 "./sipQsciQsciLexerFortran77.cpp"
#line 34 "sip/qsciabstractapis.sip"
#include <Qsci/qsciabstractapis.h>
#line 58 "./sipQsciQsciLexerFortran77.cpp"
#line 34 "sip/qsciscintilla.sip"
#include <Qsci/qsciscintilla.h>
#line 61 "./sipQsciQsciLexerFortran77.cpp"
#line 36 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 64 "./sipQsciQsciLexerFortran77.cpp"
#line 315 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 67 "./sipQsciQsciLexerFortran77.cpp"
#line 303 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 70 "./sipQsciQsciLexerFortran77.cpp"
#line 243 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qvariant.sip"
#include <qvariant.h>
#line 73 "./sipQsciQsciLexerFortran77.cpp"
#line 38 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qlist.sip"
#include <qlist.h>
#line 76 "./sipQsciQsciLexerFortran77.cpp"
#line 42 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qbytearray.sip"
#include <qbytearray.h>
#line 79 "./sipQsciQsciLexerFortran77.cpp"
#line 40 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 82 "./sipQsciQsciLexerFortran77.cpp"
#line 125 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qlist.sip"
#include <qlist.h>
#line 85 "./sipQsciQsciLexerFortran77.cpp"
#line 36 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qthread.sip"
#include <qthread.h>
#line 88 "./sipQsciQsciLexerFortran77.cpp"
#line 40 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qregexp.sip"
#include <qregexp.h>
#line 91 "./sipQsciQsciLexerFortran77.cpp"
#line 36 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qobjectdefs.sip"
#include <qobjectdefs.h>
#line 94 "./sipQsciQsciLexerFortran77.cpp"


class sipQsciLexerFortran77 : public QsciLexerFortran77
{
public:
    sipQsciLexerFortran77(QObject *);
    virtual ~sipQsciLexerFortran77();

    int qt_metacall(QMetaObject::Call,int,void **);
    void *qt_metacast(const char *);
    const QMetaObject *metaObject() const;

    /*
     * There is a protected method for every virtual method visible from
     * this class.
     */
protected:
    void setFoldCompact(bool);
    const char * language() const;
    const char * lexer() const;
    int lexerId() const;
    QColor color(int) const;
    bool eolFill(int) const;
    QFont font(int) const;
    const char * keywords(int) const;
    QString description(int) const;
    QColor paper(int) const;
    QColor defaultColor(int) const;
    bool defaultEolFill(int) const;
    QFont defaultFont(int) const;
    QColor defaultPaper(int) const;
    void refreshProperties();
    int styleBitsNeeded() const;
    void setAutoIndentStyle(int);
    void setColor(const QColor&,int);
    void setEolFill(bool,int);
    void setFont(const QFont&,int);
    void setPaper(const QColor&,int);
    bool readProperties(QSettings&,const QString&);
    bool writeProperties(QSettings&,const QString&) const;
    bool event(QEvent *);
    bool eventFilter(QObject *,QEvent *);
    void timerEvent(QTimerEvent *);
    void childEvent(QChildEvent *);
    void customEvent(QEvent *);
    void connectNotify(const char *);
    void disconnectNotify(const char *);

public:
    sipSimpleWrapper *sipPySelf;

private:
    sipQsciLexerFortran77(const sipQsciLexerFortran77 &);
    sipQsciLexerFortran77 &operator = (const sipQsciLexerFortran77 &);

    char sipPyMethods[30];
};

sipQsciLexerFortran77::sipQsciLexerFortran77(QObject *a0): QsciLexerFortran77(a0), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipQsciLexerFortran77::~sipQsciLexerFortran77()
{
    sipCommonDtor(sipPySelf);
}

const QMetaObject *sipQsciLexerFortran77::metaObject() const
{
    return sip_Qsci_qt_metaobject(sipPySelf,sipType_QsciLexerFortran77);
}

int sipQsciLexerFortran77::qt_metacall(QMetaObject::Call _c,int _id,void **_a)
{
    _id = QsciLexerFortran77::qt_metacall(_c,_id,_a);

    if (_id >= 0)
        _id = sip_Qsci_qt_metacall(sipPySelf,sipType_QsciLexerFortran77,_c,_id,_a);

    return _id;
}

void *sipQsciLexerFortran77::qt_metacast(const char *_clname)
{
    return (sip_Qsci_qt_metacast && sip_Qsci_qt_metacast(sipPySelf,sipType_QsciLexerFortran77,_clname)) ? this : QsciLexerFortran77::qt_metacast(_clname);
}

void sipQsciLexerFortran77::setFoldCompact(bool a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[0],sipPySelf,NULL,sipName_setFoldCompact);

    if (!sipMeth)
    {
        QsciLexerFortran77::setFoldCompact(a0);
        return;
    }

    typedef void (*sipVH_QtGui_6)(sip_gilstate_t,PyObject *,bool);

    ((sipVH_QtGui_6)(sipModuleAPI_Qsci_QtGui->em_virthandlers[6]))(sipGILState,sipMeth,a0);
}

const char * sipQsciLexerFortran77::language() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[1]),sipPySelf,NULL,sipName_language);

    if (!sipMeth)
        return QsciLexerFortran77::language();

    extern const char * sipVH_Qsci_13(sip_gilstate_t,PyObject *,int,sipSimpleWrapper *);

    return sipVH_Qsci_13(sipGILState,sipMeth,-74,sipPySelf);
}

const char * sipQsciLexerFortran77::lexer() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[2]),sipPySelf,NULL,sipName_lexer);

    if (!sipMeth)
        return QsciLexerFortran77::lexer();

    extern const char * sipVH_Qsci_13(sip_gilstate_t,PyObject *,int,sipSimpleWrapper *);

    return sipVH_Qsci_13(sipGILState,sipMeth,-75,sipPySelf);
}

int sipQsciLexerFortran77::lexerId() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[3]),sipPySelf,NULL,sipName_lexerId);

    if (!sipMeth)
        return QsciLexer::lexerId();

    typedef int (*sipVH_QtCore_6)(sip_gilstate_t,PyObject *);

    return ((sipVH_QtCore_6)(sipModuleAPI_Qsci_QtCore->em_virthandlers[6]))(sipGILState,sipMeth);
}

QColor sipQsciLexerFortran77::color(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[4]),sipPySelf,NULL,sipName_color);

    if (!sipMeth)
        return QsciLexer::color(a0);

    extern QColor sipVH_Qsci_11(sip_gilstate_t,PyObject *,int);

    return sipVH_Qsci_11(sipGILState,sipMeth,a0);
}

bool sipQsciLexerFortran77::eolFill(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[5]),sipPySelf,NULL,sipName_eolFill);

    if (!sipMeth)
        return QsciLexer::eolFill(a0);

    typedef bool (*sipVH_QtCore_23)(sip_gilstate_t,PyObject *,int);

    return ((sipVH_QtCore_23)(sipModuleAPI_Qsci_QtCore->em_virthandlers[23]))(sipGILState,sipMeth,a0);
}

QFont sipQsciLexerFortran77::font(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[6]),sipPySelf,NULL,sipName_font);

    if (!sipMeth)
        return QsciLexer::font(a0);

    extern QFont sipVH_Qsci_12(sip_gilstate_t,PyObject *,int);

    return sipVH_Qsci_12(sipGILState,sipMeth,a0);
}

const char * sipQsciLexerFortran77::keywords(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[7]),sipPySelf,NULL,sipName_keywords);

    if (!sipMeth)
        return QsciLexerFortran77::keywords(a0);

    typedef const char * (*sipVH_QtGui_146)(sip_gilstate_t,PyObject *,int,int,sipSimpleWrapper *);

    return ((sipVH_QtGui_146)(sipModuleAPI_Qsci_QtGui->em_virthandlers[146]))(sipGILState,sipMeth,a0,-76,sipPySelf);
}

QString sipQsciLexerFortran77::description(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[8]),sipPySelf,NULL,sipName_description);

    if (!sipMeth)
        return QsciLexerFortran77::description(a0);

    typedef QString (*sipVH_QtGui_111)(sip_gilstate_t,PyObject *,int);

    return ((sipVH_QtGui_111)(sipModuleAPI_Qsci_QtGui->em_virthandlers[111]))(sipGILState,sipMeth,a0);
}

QColor sipQsciLexerFortran77::paper(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[9]),sipPySelf,NULL,sipName_paper);

    if (!sipMeth)
        return QsciLexer::paper(a0);

    extern QColor sipVH_Qsci_11(sip_gilstate_t,PyObject *,int);

    return sipVH_Qsci_11(sipGILState,sipMeth,a0);
}

QColor sipQsciLexerFortran77::defaultColor(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[10]),sipPySelf,NULL,sipName_defaultColor);

    if (!sipMeth)
        return QsciLexerFortran77::defaultColor(a0);

    extern QColor sipVH_Qsci_11(sip_gilstate_t,PyObject *,int);

    return sipVH_Qsci_11(sipGILState,sipMeth,a0);
}

bool sipQsciLexerFortran77::defaultEolFill(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[11]),sipPySelf,NULL,sipName_defaultEolFill);

    if (!sipMeth)
        return QsciLexerFortran77::defaultEolFill(a0);

    typedef bool (*sipVH_QtCore_23)(sip_gilstate_t,PyObject *,int);

    return ((sipVH_QtCore_23)(sipModuleAPI_Qsci_QtCore->em_virthandlers[23]))(sipGILState,sipMeth,a0);
}

QFont sipQsciLexerFortran77::defaultFont(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[12]),sipPySelf,NULL,sipName_defaultFont);

    if (!sipMeth)
        return QsciLexerFortran77::defaultFont(a0);

    extern QFont sipVH_Qsci_12(sip_gilstate_t,PyObject *,int);

    return sipVH_Qsci_12(sipGILState,sipMeth,a0);
}

QColor sipQsciLexerFortran77::defaultPaper(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[13]),sipPySelf,NULL,sipName_defaultPaper);

    if (!sipMeth)
        return QsciLexerFortran77::defaultPaper(a0);

    extern QColor sipVH_Qsci_11(sip_gilstate_t,PyObject *,int);

    return sipVH_Qsci_11(sipGILState,sipMeth,a0);
}

void sipQsciLexerFortran77::refreshProperties()
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[14],sipPySelf,NULL,sipName_refreshProperties);

    if (!sipMeth)
    {
        QsciLexerFortran77::refreshProperties();
        return;
    }

    typedef void (*sipVH_QtCore_11)(sip_gilstate_t,PyObject *);

    ((sipVH_QtCore_11)(sipModuleAPI_Qsci_QtCore->em_virthandlers[11]))(sipGILState,sipMeth);
}

int sipQsciLexerFortran77::styleBitsNeeded() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[15]),sipPySelf,NULL,sipName_styleBitsNeeded);

    if (!sipMeth)
        return QsciLexer::styleBitsNeeded();

    typedef int (*sipVH_QtCore_6)(sip_gilstate_t,PyObject *);

    return ((sipVH_QtCore_6)(sipModuleAPI_Qsci_QtCore->em_virthandlers[6]))(sipGILState,sipMeth);
}

void sipQsciLexerFortran77::setAutoIndentStyle(int a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[16],sipPySelf,NULL,sipName_setAutoIndentStyle);

    if (!sipMeth)
    {
        QsciLexer::setAutoIndentStyle(a0);
        return;
    }

    typedef void (*sipVH_QtCore_4)(sip_gilstate_t,PyObject *,int);

    ((sipVH_QtCore_4)(sipModuleAPI_Qsci_QtCore->em_virthandlers[4]))(sipGILState,sipMeth,a0);
}

void sipQsciLexerFortran77::setColor(const QColor& a0,int a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[17],sipPySelf,NULL,sipName_setColor);

    if (!sipMeth)
    {
        QsciLexer::setColor(a0,a1);
        return;
    }

    extern void sipVH_Qsci_8(sip_gilstate_t,PyObject *,const QColor&,int);

    sipVH_Qsci_8(sipGILState,sipMeth,a0,a1);
}

void sipQsciLexerFortran77::setEolFill(bool a0,int a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[18],sipPySelf,NULL,sipName_setEolFill);

    if (!sipMeth)
    {
        QsciLexer::setEolFill(a0,a1);
        return;
    }

    extern void sipVH_Qsci_10(sip_gilstate_t,PyObject *,bool,int);

    sipVH_Qsci_10(sipGILState,sipMeth,a0,a1);
}

void sipQsciLexerFortran77::setFont(const QFont& a0,int a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[19],sipPySelf,NULL,sipName_setFont);

    if (!sipMeth)
    {
        QsciLexer::setFont(a0,a1);
        return;
    }

    extern void sipVH_Qsci_9(sip_gilstate_t,PyObject *,const QFont&,int);

    sipVH_Qsci_9(sipGILState,sipMeth,a0,a1);
}

void sipQsciLexerFortran77::setPaper(const QColor& a0,int a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[20],sipPySelf,NULL,sipName_setPaper);

    if (!sipMeth)
    {
        QsciLexer::setPaper(a0,a1);
        return;
    }

    extern void sipVH_Qsci_8(sip_gilstate_t,PyObject *,const QColor&,int);

    sipVH_Qsci_8(sipGILState,sipMeth,a0,a1);
}

bool sipQsciLexerFortran77::readProperties(QSettings& a0,const QString& a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[21],sipPySelf,NULL,sipName_readProperties);

    if (!sipMeth)
        return QsciLexerFortran77::readProperties(a0,a1);

    extern bool sipVH_Qsci_7(sip_gilstate_t,PyObject *,QSettings&,const QString&);

    return sipVH_Qsci_7(sipGILState,sipMeth,a0,a1);
}

bool sipQsciLexerFortran77::writeProperties(QSettings& a0,const QString& a1) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[22]),sipPySelf,NULL,sipName_writeProperties);

    if (!sipMeth)
        return QsciLexerFortran77::writeProperties(a0,a1);

    extern bool sipVH_Qsci_7(sip_gilstate_t,PyObject *,QSettings&,const QString&);

    return sipVH_Qsci_7(sipGILState,sipMeth,a0,a1);
}

bool sipQsciLexerFortran77::event(QEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[23],sipPySelf,NULL,sipName_event);

    if (!sipMeth)
        return QObject::event(a0);

    typedef bool (*sipVH_QtCore_5)(sip_gilstate_t,PyObject *,QEvent *);

    return ((sipVH_QtCore_5)(sipModuleAPI_Qsci_QtCore->em_virthandlers[5]))(sipGILState,sipMeth,a0);
}

bool sipQsciLexerFortran77::eventFilter(QObject *a0,QEvent *a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[24],sipPySelf,NULL,sipName_eventFilter);

    if (!sipMeth)
        return QObject::eventFilter(a0,a1);

    typedef bool (*sipVH_QtCore_18)(sip_gilstate_t,PyObject *,QObject *,QEvent *);

    return ((sipVH_QtCore_18)(sipModuleAPI_Qsci_QtCore->em_virthandlers[18]))(sipGILState,sipMeth,a0,a1);
}

void sipQsciLexerFortran77::timerEvent(QTimerEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[25],sipPySelf,NULL,sipName_timerEvent);

    if (!sipMeth)
    {
        QObject::timerEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_9)(sip_gilstate_t,PyObject *,QTimerEvent *);

    ((sipVH_QtCore_9)(sipModuleAPI_Qsci_QtCore->em_virthandlers[9]))(sipGILState,sipMeth,a0);
}

void sipQsciLexerFortran77::childEvent(QChildEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[26],sipPySelf,NULL,sipName_childEvent);

    if (!sipMeth)
    {
        QObject::childEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_25)(sip_gilstate_t,PyObject *,QChildEvent *);

    ((sipVH_QtCore_25)(sipModuleAPI_Qsci_QtCore->em_virthandlers[25]))(sipGILState,sipMeth,a0);
}

void sipQsciLexerFortran77::customEvent(QEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[27],sipPySelf,NULL,sipName_customEvent);

    if (!sipMeth)
    {
        QObject::customEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_17)(sip_gilstate_t,PyObject *,QEvent *);

    ((sipVH_QtCore_17)(sipModuleAPI_Qsci_QtCore->em_virthandlers[17]))(sipGILState,sipMeth,a0);
}

void sipQsciLexerFortran77::connectNotify(const char *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[28],sipPySelf,NULL,sipName_connectNotify);

    if (!sipMeth)
    {
        QObject::connectNotify(a0);
        return;
    }

    typedef void (*sipVH_QtCore_24)(sip_gilstate_t,PyObject *,const char *);

    ((sipVH_QtCore_24)(sipModuleAPI_Qsci_QtCore->em_virthandlers[24]))(sipGILState,sipMeth,a0);
}

void sipQsciLexerFortran77::disconnectNotify(const char *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[29],sipPySelf,NULL,sipName_disconnectNotify);

    if (!sipMeth)
    {
        QObject::disconnectNotify(a0);
        return;
    }

    typedef void (*sipVH_QtCore_24)(sip_gilstate_t,PyObject *,const char *);

    ((sipVH_QtCore_24)(sipModuleAPI_Qsci_QtCore->em_virthandlers[24]))(sipGILState,sipMeth,a0);
}


PyDoc_STRVAR(doc_QsciLexerFortran77_language, "QsciLexerFortran77.language() -> str");

extern "C" {static PyObject *meth_QsciLexerFortran77_language(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerFortran77_language(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QsciLexerFortran77 *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QsciLexerFortran77, &sipCpp))
        {
            const char *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = (sipSelfWasArg ? sipCpp->QsciLexerFortran77::language() : sipCpp->language());
            Py_END_ALLOW_THREADS

            if (sipRes == NULL)
            {
                Py_INCREF(Py_None);
                return Py_None;
            }

            return SIPBytes_FromString(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerFortran77, sipName_language, doc_QsciLexerFortran77_language);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerFortran77_lexer, "QsciLexerFortran77.lexer() -> str");

extern "C" {static PyObject *meth_QsciLexerFortran77_lexer(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerFortran77_lexer(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QsciLexerFortran77 *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QsciLexerFortran77, &sipCpp))
        {
            const char *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = (sipSelfWasArg ? sipCpp->QsciLexerFortran77::lexer() : sipCpp->lexer());
            Py_END_ALLOW_THREADS

            if (sipRes == NULL)
            {
                Py_INCREF(Py_None);
                return Py_None;
            }

            return SIPBytes_FromString(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerFortran77, sipName_lexer, doc_QsciLexerFortran77_lexer);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerFortran77_defaultColor, "QsciLexerFortran77.defaultColor(int) -> QColor");

extern "C" {static PyObject *meth_QsciLexerFortran77_defaultColor(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerFortran77_defaultColor(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        int a0;
        QsciLexerFortran77 *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QsciLexerFortran77, &sipCpp, &a0))
        {
            QColor *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QColor((sipSelfWasArg ? sipCpp->QsciLexerFortran77::defaultColor(a0) : sipCpp->defaultColor(a0)));
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QColor,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerFortran77, sipName_defaultColor, doc_QsciLexerFortran77_defaultColor);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerFortran77_defaultEolFill, "QsciLexerFortran77.defaultEolFill(int) -> bool");

extern "C" {static PyObject *meth_QsciLexerFortran77_defaultEolFill(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerFortran77_defaultEolFill(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        int a0;
        QsciLexerFortran77 *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QsciLexerFortran77, &sipCpp, &a0))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = (sipSelfWasArg ? sipCpp->QsciLexerFortran77::defaultEolFill(a0) : sipCpp->defaultEolFill(a0));
            Py_END_ALLOW_THREADS

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerFortran77, sipName_defaultEolFill, doc_QsciLexerFortran77_defaultEolFill);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerFortran77_defaultFont, "QsciLexerFortran77.defaultFont(int) -> QFont");

extern "C" {static PyObject *meth_QsciLexerFortran77_defaultFont(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerFortran77_defaultFont(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        int a0;
        QsciLexerFortran77 *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QsciLexerFortran77, &sipCpp, &a0))
        {
            QFont *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QFont((sipSelfWasArg ? sipCpp->QsciLexerFortran77::defaultFont(a0) : sipCpp->defaultFont(a0)));
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QFont,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerFortran77, sipName_defaultFont, doc_QsciLexerFortran77_defaultFont);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerFortran77_defaultPaper, "QsciLexerFortran77.defaultPaper(int) -> QColor");

extern "C" {static PyObject *meth_QsciLexerFortran77_defaultPaper(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerFortran77_defaultPaper(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        int a0;
        QsciLexerFortran77 *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QsciLexerFortran77, &sipCpp, &a0))
        {
            QColor *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QColor((sipSelfWasArg ? sipCpp->QsciLexerFortran77::defaultPaper(a0) : sipCpp->defaultPaper(a0)));
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QColor,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerFortran77, sipName_defaultPaper, doc_QsciLexerFortran77_defaultPaper);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerFortran77_keywords, "QsciLexerFortran77.keywords(int) -> str");

extern "C" {static PyObject *meth_QsciLexerFortran77_keywords(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerFortran77_keywords(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        int a0;
        QsciLexerFortran77 *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QsciLexerFortran77, &sipCpp, &a0))
        {
            const char *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = (sipSelfWasArg ? sipCpp->QsciLexerFortran77::keywords(a0) : sipCpp->keywords(a0));
            Py_END_ALLOW_THREADS

            if (sipRes == NULL)
            {
                Py_INCREF(Py_None);
                return Py_None;
            }

            return SIPBytes_FromString(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerFortran77, sipName_keywords, doc_QsciLexerFortran77_keywords);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerFortran77_description, "QsciLexerFortran77.description(int) -> QString");

extern "C" {static PyObject *meth_QsciLexerFortran77_description(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerFortran77_description(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        int a0;
        QsciLexerFortran77 *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QsciLexerFortran77, &sipCpp, &a0))
        {
            QString *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QString((sipSelfWasArg ? sipCpp->QsciLexerFortran77::description(a0) : sipCpp->description(a0)));
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerFortran77, sipName_description, doc_QsciLexerFortran77_description);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerFortran77_refreshProperties, "QsciLexerFortran77.refreshProperties()");

extern "C" {static PyObject *meth_QsciLexerFortran77_refreshProperties(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerFortran77_refreshProperties(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QsciLexerFortran77 *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QsciLexerFortran77, &sipCpp))
        {
            Py_BEGIN_ALLOW_THREADS
            (sipSelfWasArg ? sipCpp->QsciLexerFortran77::refreshProperties() : sipCpp->refreshProperties());
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerFortran77, sipName_refreshProperties, doc_QsciLexerFortran77_refreshProperties);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerFortran77_foldCompact, "QsciLexerFortran77.foldCompact() -> bool");

extern "C" {static PyObject *meth_QsciLexerFortran77_foldCompact(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerFortran77_foldCompact(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QsciLexerFortran77 *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QsciLexerFortran77, &sipCpp))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->foldCompact();
            Py_END_ALLOW_THREADS

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerFortran77, sipName_foldCompact, doc_QsciLexerFortran77_foldCompact);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerFortran77_setFoldCompact, "QsciLexerFortran77.setFoldCompact(bool)");

extern "C" {static PyObject *meth_QsciLexerFortran77_setFoldCompact(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerFortran77_setFoldCompact(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        bool a0;
        QsciLexerFortran77 *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QsciLexerFortran77, &sipCpp, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            (sipSelfWasArg ? sipCpp->QsciLexerFortran77::setFoldCompact(a0) : sipCpp->setFoldCompact(a0));
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerFortran77, sipName_setFoldCompact, doc_QsciLexerFortran77_setFoldCompact);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerFortran77_readProperties, "QsciLexerFortran77.readProperties(QSettings, QString) -> bool");

extern "C" {static PyObject *meth_QsciLexerFortran77_readProperties(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerFortran77_readProperties(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QSettings * a0;
        const QString * a1;
        int a1State = 0;
        QsciLexerFortran77 *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ9J1", &sipSelf, sipType_QsciLexerFortran77, &sipCpp, sipType_QSettings, &a0, sipType_QString,&a1, &a1State))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = (sipSelfWasArg ? sipCpp->QsciLexerFortran77::readProperties(*a0,*a1) : sipCpp->readProperties(*a0,*a1));
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast<QString *>(a1),sipType_QString,a1State);

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerFortran77, sipName_readProperties, doc_QsciLexerFortran77_readProperties);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerFortran77_writeProperties, "QsciLexerFortran77.writeProperties(QSettings, QString) -> bool");

extern "C" {static PyObject *meth_QsciLexerFortran77_writeProperties(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerFortran77_writeProperties(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QSettings * a0;
        const QString * a1;
        int a1State = 0;
        QsciLexerFortran77 *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ9J1", &sipSelf, sipType_QsciLexerFortran77, &sipCpp, sipType_QSettings, &a0, sipType_QString,&a1, &a1State))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = (sipSelfWasArg ? sipCpp->QsciLexerFortran77::writeProperties(*a0,*a1) : sipCpp->writeProperties(*a0,*a1));
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast<QString *>(a1),sipType_QString,a1State);

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerFortran77, sipName_writeProperties, doc_QsciLexerFortran77_writeProperties);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QsciLexerFortran77(void *, const sipTypeDef *);}
static void *cast_QsciLexerFortran77(void *ptr, const sipTypeDef *targetType)
{
    void *res;

    if (targetType == sipType_QsciLexerFortran77)
        return ptr;

    if ((res = ((const sipClassTypeDef *)sipType_QsciLexer)->ctd_cast((QsciLexer *)(QsciLexerFortran77 *)ptr,targetType)) != NULL)
        return res;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QsciLexerFortran77(void *, int);}
static void release_QsciLexerFortran77(void *sipCppV,int)
{
    Py_BEGIN_ALLOW_THREADS

    QsciLexerFortran77 *sipCpp = reinterpret_cast<QsciLexerFortran77 *>(sipCppV);

    if (QThread::currentThread() == sipCpp->thread())
        delete sipCpp;
    else
        sipCpp->deleteLater();

    Py_END_ALLOW_THREADS
}


extern "C" {static void dealloc_QsciLexerFortran77(sipSimpleWrapper *);}
static void dealloc_QsciLexerFortran77(sipSimpleWrapper *sipSelf)
{
    if (sipIsDerived(sipSelf))
        reinterpret_cast<sipQsciLexerFortran77 *>(sipGetAddress(sipSelf))->sipPySelf = NULL;

    if (sipIsPyOwned(sipSelf))
    {
        release_QsciLexerFortran77(sipGetAddress(sipSelf),sipSelf->flags);
    }
}


extern "C" {static void *init_QsciLexerFortran77(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_QsciLexerFortran77(sipSimpleWrapper *sipSelf, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **sipOwner, PyObject **sipParseErr)
{
    sipQsciLexerFortran77 *sipCpp = 0;

    {
        QObject * a0 = 0;

        static const char *sipKwdList[] = {
            sipName_parent,
        };

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, sipKwdList, sipUnused, "|JH", sipType_QObject, &a0, sipOwner))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new sipQsciLexerFortran77(a0);
            Py_END_ALLOW_THREADS

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    return NULL;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QsciLexerFortran77[] = {{7, 255, 1}};


static PyMethodDef methods_QsciLexerFortran77[] = {
    {SIP_MLNAME_CAST(sipName_defaultColor), meth_QsciLexerFortran77_defaultColor, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerFortran77_defaultColor)},
    {SIP_MLNAME_CAST(sipName_defaultEolFill), meth_QsciLexerFortran77_defaultEolFill, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerFortran77_defaultEolFill)},
    {SIP_MLNAME_CAST(sipName_defaultFont), meth_QsciLexerFortran77_defaultFont, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerFortran77_defaultFont)},
    {SIP_MLNAME_CAST(sipName_defaultPaper), meth_QsciLexerFortran77_defaultPaper, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerFortran77_defaultPaper)},
    {SIP_MLNAME_CAST(sipName_description), meth_QsciLexerFortran77_description, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerFortran77_description)},
    {SIP_MLNAME_CAST(sipName_foldCompact), meth_QsciLexerFortran77_foldCompact, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerFortran77_foldCompact)},
    {SIP_MLNAME_CAST(sipName_keywords), meth_QsciLexerFortran77_keywords, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerFortran77_keywords)},
    {SIP_MLNAME_CAST(sipName_language), meth_QsciLexerFortran77_language, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerFortran77_language)},
    {SIP_MLNAME_CAST(sipName_lexer), meth_QsciLexerFortran77_lexer, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerFortran77_lexer)},
    {SIP_MLNAME_CAST(sipName_readProperties), meth_QsciLexerFortran77_readProperties, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerFortran77_readProperties)},
    {SIP_MLNAME_CAST(sipName_refreshProperties), meth_QsciLexerFortran77_refreshProperties, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerFortran77_refreshProperties)},
    {SIP_MLNAME_CAST(sipName_setFoldCompact), meth_QsciLexerFortran77_setFoldCompact, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerFortran77_setFoldCompact)},
    {SIP_MLNAME_CAST(sipName_writeProperties), meth_QsciLexerFortran77_writeProperties, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerFortran77_writeProperties)}
};

static sipEnumMemberDef enummembers_QsciLexerFortran77[] = {
    {sipName_Comment, QsciLexerFortran77::Comment, -1},
    {sipName_Continuation, QsciLexerFortran77::Continuation, -1},
    {sipName_Default, QsciLexerFortran77::Default, -1},
    {sipName_DottedOperator, QsciLexerFortran77::DottedOperator, -1},
    {sipName_DoubleQuotedString, QsciLexerFortran77::DoubleQuotedString, -1},
    {sipName_ExtendedFunction, QsciLexerFortran77::ExtendedFunction, -1},
    {sipName_Identifier, QsciLexerFortran77::Identifier, -1},
    {sipName_IntrinsicFunction, QsciLexerFortran77::IntrinsicFunction, -1},
    {sipName_Keyword, QsciLexerFortran77::Keyword, -1},
    {sipName_Label, QsciLexerFortran77::Label, -1},
    {sipName_Number, QsciLexerFortran77::Number, -1},
    {sipName_Operator, QsciLexerFortran77::Operator, -1},
    {sipName_PreProcessor, QsciLexerFortran77::PreProcessor, -1},
    {sipName_SingleQuotedString, QsciLexerFortran77::SingleQuotedString, -1},
    {sipName_UnclosedString, QsciLexerFortran77::UnclosedString, -1},
};

PyDoc_STRVAR(doc_QsciLexerFortran77, "\1QsciLexerFortran77(QObject parent=None)");


pyqt4ClassTypeDef sipTypeDef_Qsci_QsciLexerFortran77 = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_SCC|SIP_TYPE_CLASS,
        sipNameNr_QsciLexerFortran77,
        {0}
    },
    {
        sipNameNr_QsciLexerFortran77,
        {0, 0, 1},
        13, methods_QsciLexerFortran77,
        15, enummembers_QsciLexerFortran77,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    doc_QsciLexerFortran77,
    -1,
    -1,
    supers_QsciLexerFortran77,
    0,
    init_QsciLexerFortran77,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QsciLexerFortran77,
    0,
    0,
    0,
    release_QsciLexerFortran77,
    cast_QsciLexerFortran77,
    0,
    0,
    0
},
    &QsciLexerFortran77::staticMetaObject,
    0,
    0
};
