/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.12.5-snapshot-c2987628087f on Thu Sep  1 02:20:43 2011
 *
 * Copyright (c) 2011 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of QScintilla.
 * 
 * This file may be used under the terms of the GNU General Public
 * License versions 2.0 or 3.0 as published by the Free Software
 * Foundation and appearing in the files LICENSE.GPL2 and LICENSE.GPL3
 * included in the packaging of this file.  Alternatively you may (at
 * your option) use any later version of the GNU General Public
 * License if such license has been publicly approved by Riverbank
 * Computing Limited (or its successors, if any) and the KDE Free Qt
 * Foundation. In addition, as a special exception, Riverbank gives you
 * certain additional rights. These rights are described in the Riverbank
 * GPL Exception version 1.1, which can be found in the file
 * GPL_EXCEPTION.txt in this package.
 * 
 * Please review the following information to ensure GNU General
 * Public Licensing requirements will be met:
 * http://trolltech.com/products/qt/licenses/licensing/opensource/. If
 * you are unsure which license is appropriate for your use, please
 * review the following information:
 * http://trolltech.com/products/qt/licenses/licensing/licensingoverview
 * or contact the sales department at sales@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQsci.h"

#line 34 "sip/qscilexersql.sip"
#include <Qsci/qscilexersql.h>
#line 39 "./sipQsciQsciLexerSQL.cpp"

#line 39 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qobject.sip"
#include <qobject.h>
#line 43 "./sipQsciQsciLexerSQL.cpp"
#line 36 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qsettings.sip"
#include <qsettings.h>
#line 46 "./sipQsciQsciLexerSQL.cpp"
#line 41 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qstring.sip"
#include <qstring.h>
#line 49 "./sipQsciQsciLexerSQL.cpp"
#line 40 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtGui/qcolor.sip"
#include <qcolor.h>
#line 52 "./sipQsciQsciLexerSQL.cpp"
#line 40 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtGui/qfont.sip"
#include <qfont.h>
#line 55 "./sipQsciQsciLexerSQL.cpp"
#line 34 "sip/qsciabstractapis.sip"
#include <Qsci/qsciabstractapis.h>
#line 58 "./sipQsciQsciLexerSQL.cpp"
#line 34 "sip/qsciscintilla.sip"
#include <Qsci/qsciscintilla.h>
#line 61 "./sipQsciQsciLexerSQL.cpp"
#line 36 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 64 "./sipQsciQsciLexerSQL.cpp"
#line 315 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 67 "./sipQsciQsciLexerSQL.cpp"
#line 303 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 70 "./sipQsciQsciLexerSQL.cpp"
#line 243 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qvariant.sip"
#include <qvariant.h>
#line 73 "./sipQsciQsciLexerSQL.cpp"
#line 38 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qlist.sip"
#include <qlist.h>
#line 76 "./sipQsciQsciLexerSQL.cpp"
#line 42 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qbytearray.sip"
#include <qbytearray.h>
#line 79 "./sipQsciQsciLexerSQL.cpp"
#line 40 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 82 "./sipQsciQsciLexerSQL.cpp"
#line 125 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qlist.sip"
#include <qlist.h>
#line 85 "./sipQsciQsciLexerSQL.cpp"
#line 36 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qthread.sip"
#include <qthread.h>
#line 88 "./sipQsciQsciLexerSQL.cpp"
#line 40 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qregexp.sip"
#include <qregexp.h>
#line 91 "./sipQsciQsciLexerSQL.cpp"
#line 36 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qobjectdefs.sip"
#include <qobjectdefs.h>
#line 94 "./sipQsciQsciLexerSQL.cpp"


class sipQsciLexerSQL : public QsciLexerSQL
{
public:
    sipQsciLexerSQL(QObject *);
    virtual ~sipQsciLexerSQL();

    int qt_metacall(QMetaObject::Call,int,void **);
    void *qt_metacast(const char *);
    const QMetaObject *metaObject() const;

    /*
     * There is a protected method for every virtual method visible from
     * this class.
     */
protected:
    void setBackslashEscapes(bool);
    void setFoldComments(bool);
    void setFoldCompact(bool);
    const char * language() const;
    const char * lexer() const;
    int lexerId() const;
    QColor color(int) const;
    bool eolFill(int) const;
    QFont font(int) const;
    const char * keywords(int) const;
    QString description(int) const;
    QColor paper(int) const;
    QColor defaultColor(int) const;
    bool defaultEolFill(int) const;
    QFont defaultFont(int) const;
    QColor defaultPaper(int) const;
    void refreshProperties();
    int styleBitsNeeded() const;
    void setAutoIndentStyle(int);
    void setColor(const QColor&,int);
    void setEolFill(bool,int);
    void setFont(const QFont&,int);
    void setPaper(const QColor&,int);
    bool readProperties(QSettings&,const QString&);
    bool writeProperties(QSettings&,const QString&) const;
    bool event(QEvent *);
    bool eventFilter(QObject *,QEvent *);
    void timerEvent(QTimerEvent *);
    void childEvent(QChildEvent *);
    void customEvent(QEvent *);
    void connectNotify(const char *);
    void disconnectNotify(const char *);

public:
    sipSimpleWrapper *sipPySelf;

private:
    sipQsciLexerSQL(const sipQsciLexerSQL &);
    sipQsciLexerSQL &operator = (const sipQsciLexerSQL &);

    char sipPyMethods[32];
};

sipQsciLexerSQL::sipQsciLexerSQL(QObject *a0): QsciLexerSQL(a0), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipQsciLexerSQL::~sipQsciLexerSQL()
{
    sipCommonDtor(sipPySelf);
}

const QMetaObject *sipQsciLexerSQL::metaObject() const
{
    return sip_Qsci_qt_metaobject(sipPySelf,sipType_QsciLexerSQL);
}

int sipQsciLexerSQL::qt_metacall(QMetaObject::Call _c,int _id,void **_a)
{
    _id = QsciLexerSQL::qt_metacall(_c,_id,_a);

    if (_id >= 0)
        _id = sip_Qsci_qt_metacall(sipPySelf,sipType_QsciLexerSQL,_c,_id,_a);

    return _id;
}

void *sipQsciLexerSQL::qt_metacast(const char *_clname)
{
    return (sip_Qsci_qt_metacast && sip_Qsci_qt_metacast(sipPySelf,sipType_QsciLexerSQL,_clname)) ? this : QsciLexerSQL::qt_metacast(_clname);
}

void sipQsciLexerSQL::setBackslashEscapes(bool a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[0],sipPySelf,NULL,sipName_setBackslashEscapes);

    if (!sipMeth)
    {
        QsciLexerSQL::setBackslashEscapes(a0);
        return;
    }

    typedef void (*sipVH_QtGui_6)(sip_gilstate_t,PyObject *,bool);

    ((sipVH_QtGui_6)(sipModuleAPI_Qsci_QtGui->em_virthandlers[6]))(sipGILState,sipMeth,a0);
}

void sipQsciLexerSQL::setFoldComments(bool a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[1],sipPySelf,NULL,sipName_setFoldComments);

    if (!sipMeth)
    {
        QsciLexerSQL::setFoldComments(a0);
        return;
    }

    typedef void (*sipVH_QtGui_6)(sip_gilstate_t,PyObject *,bool);

    ((sipVH_QtGui_6)(sipModuleAPI_Qsci_QtGui->em_virthandlers[6]))(sipGILState,sipMeth,a0);
}

void sipQsciLexerSQL::setFoldCompact(bool a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[2],sipPySelf,NULL,sipName_setFoldCompact);

    if (!sipMeth)
    {
        QsciLexerSQL::setFoldCompact(a0);
        return;
    }

    typedef void (*sipVH_QtGui_6)(sip_gilstate_t,PyObject *,bool);

    ((sipVH_QtGui_6)(sipModuleAPI_Qsci_QtGui->em_virthandlers[6]))(sipGILState,sipMeth,a0);
}

const char * sipQsciLexerSQL::language() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[3]),sipPySelf,NULL,sipName_language);

    if (!sipMeth)
        return QsciLexerSQL::language();

    extern const char * sipVH_Qsci_13(sip_gilstate_t,PyObject *,int,sipSimpleWrapper *);

    return sipVH_Qsci_13(sipGILState,sipMeth,-20,sipPySelf);
}

const char * sipQsciLexerSQL::lexer() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[4]),sipPySelf,NULL,sipName_lexer);

    if (!sipMeth)
        return QsciLexerSQL::lexer();

    extern const char * sipVH_Qsci_13(sip_gilstate_t,PyObject *,int,sipSimpleWrapper *);

    return sipVH_Qsci_13(sipGILState,sipMeth,-21,sipPySelf);
}

int sipQsciLexerSQL::lexerId() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[5]),sipPySelf,NULL,sipName_lexerId);

    if (!sipMeth)
        return QsciLexer::lexerId();

    typedef int (*sipVH_QtCore_6)(sip_gilstate_t,PyObject *);

    return ((sipVH_QtCore_6)(sipModuleAPI_Qsci_QtCore->em_virthandlers[6]))(sipGILState,sipMeth);
}

QColor sipQsciLexerSQL::color(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[6]),sipPySelf,NULL,sipName_color);

    if (!sipMeth)
        return QsciLexer::color(a0);

    extern QColor sipVH_Qsci_11(sip_gilstate_t,PyObject *,int);

    return sipVH_Qsci_11(sipGILState,sipMeth,a0);
}

bool sipQsciLexerSQL::eolFill(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[7]),sipPySelf,NULL,sipName_eolFill);

    if (!sipMeth)
        return QsciLexer::eolFill(a0);

    typedef bool (*sipVH_QtCore_23)(sip_gilstate_t,PyObject *,int);

    return ((sipVH_QtCore_23)(sipModuleAPI_Qsci_QtCore->em_virthandlers[23]))(sipGILState,sipMeth,a0);
}

QFont sipQsciLexerSQL::font(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[8]),sipPySelf,NULL,sipName_font);

    if (!sipMeth)
        return QsciLexer::font(a0);

    extern QFont sipVH_Qsci_12(sip_gilstate_t,PyObject *,int);

    return sipVH_Qsci_12(sipGILState,sipMeth,a0);
}

const char * sipQsciLexerSQL::keywords(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[9]),sipPySelf,NULL,sipName_keywords);

    if (!sipMeth)
        return QsciLexerSQL::keywords(a0);

    typedef const char * (*sipVH_QtGui_146)(sip_gilstate_t,PyObject *,int,int,sipSimpleWrapper *);

    return ((sipVH_QtGui_146)(sipModuleAPI_Qsci_QtGui->em_virthandlers[146]))(sipGILState,sipMeth,a0,-22,sipPySelf);
}

QString sipQsciLexerSQL::description(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[10]),sipPySelf,NULL,sipName_description);

    if (!sipMeth)
        return QsciLexerSQL::description(a0);

    typedef QString (*sipVH_QtGui_111)(sip_gilstate_t,PyObject *,int);

    return ((sipVH_QtGui_111)(sipModuleAPI_Qsci_QtGui->em_virthandlers[111]))(sipGILState,sipMeth,a0);
}

QColor sipQsciLexerSQL::paper(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[11]),sipPySelf,NULL,sipName_paper);

    if (!sipMeth)
        return QsciLexer::paper(a0);

    extern QColor sipVH_Qsci_11(sip_gilstate_t,PyObject *,int);

    return sipVH_Qsci_11(sipGILState,sipMeth,a0);
}

QColor sipQsciLexerSQL::defaultColor(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[12]),sipPySelf,NULL,sipName_defaultColor);

    if (!sipMeth)
        return QsciLexerSQL::defaultColor(a0);

    extern QColor sipVH_Qsci_11(sip_gilstate_t,PyObject *,int);

    return sipVH_Qsci_11(sipGILState,sipMeth,a0);
}

bool sipQsciLexerSQL::defaultEolFill(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[13]),sipPySelf,NULL,sipName_defaultEolFill);

    if (!sipMeth)
        return QsciLexerSQL::defaultEolFill(a0);

    typedef bool (*sipVH_QtCore_23)(sip_gilstate_t,PyObject *,int);

    return ((sipVH_QtCore_23)(sipModuleAPI_Qsci_QtCore->em_virthandlers[23]))(sipGILState,sipMeth,a0);
}

QFont sipQsciLexerSQL::defaultFont(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[14]),sipPySelf,NULL,sipName_defaultFont);

    if (!sipMeth)
        return QsciLexerSQL::defaultFont(a0);

    extern QFont sipVH_Qsci_12(sip_gilstate_t,PyObject *,int);

    return sipVH_Qsci_12(sipGILState,sipMeth,a0);
}

QColor sipQsciLexerSQL::defaultPaper(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[15]),sipPySelf,NULL,sipName_defaultPaper);

    if (!sipMeth)
        return QsciLexerSQL::defaultPaper(a0);

    extern QColor sipVH_Qsci_11(sip_gilstate_t,PyObject *,int);

    return sipVH_Qsci_11(sipGILState,sipMeth,a0);
}

void sipQsciLexerSQL::refreshProperties()
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[16],sipPySelf,NULL,sipName_refreshProperties);

    if (!sipMeth)
    {
        QsciLexerSQL::refreshProperties();
        return;
    }

    typedef void (*sipVH_QtCore_11)(sip_gilstate_t,PyObject *);

    ((sipVH_QtCore_11)(sipModuleAPI_Qsci_QtCore->em_virthandlers[11]))(sipGILState,sipMeth);
}

int sipQsciLexerSQL::styleBitsNeeded() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[17]),sipPySelf,NULL,sipName_styleBitsNeeded);

    if (!sipMeth)
        return QsciLexer::styleBitsNeeded();

    typedef int (*sipVH_QtCore_6)(sip_gilstate_t,PyObject *);

    return ((sipVH_QtCore_6)(sipModuleAPI_Qsci_QtCore->em_virthandlers[6]))(sipGILState,sipMeth);
}

void sipQsciLexerSQL::setAutoIndentStyle(int a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[18],sipPySelf,NULL,sipName_setAutoIndentStyle);

    if (!sipMeth)
    {
        QsciLexer::setAutoIndentStyle(a0);
        return;
    }

    typedef void (*sipVH_QtCore_4)(sip_gilstate_t,PyObject *,int);

    ((sipVH_QtCore_4)(sipModuleAPI_Qsci_QtCore->em_virthandlers[4]))(sipGILState,sipMeth,a0);
}

void sipQsciLexerSQL::setColor(const QColor& a0,int a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[19],sipPySelf,NULL,sipName_setColor);

    if (!sipMeth)
    {
        QsciLexer::setColor(a0,a1);
        return;
    }

    extern void sipVH_Qsci_8(sip_gilstate_t,PyObject *,const QColor&,int);

    sipVH_Qsci_8(sipGILState,sipMeth,a0,a1);
}

void sipQsciLexerSQL::setEolFill(bool a0,int a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[20],sipPySelf,NULL,sipName_setEolFill);

    if (!sipMeth)
    {
        QsciLexer::setEolFill(a0,a1);
        return;
    }

    extern void sipVH_Qsci_10(sip_gilstate_t,PyObject *,bool,int);

    sipVH_Qsci_10(sipGILState,sipMeth,a0,a1);
}

void sipQsciLexerSQL::setFont(const QFont& a0,int a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[21],sipPySelf,NULL,sipName_setFont);

    if (!sipMeth)
    {
        QsciLexer::setFont(a0,a1);
        return;
    }

    extern void sipVH_Qsci_9(sip_gilstate_t,PyObject *,const QFont&,int);

    sipVH_Qsci_9(sipGILState,sipMeth,a0,a1);
}

void sipQsciLexerSQL::setPaper(const QColor& a0,int a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[22],sipPySelf,NULL,sipName_setPaper);

    if (!sipMeth)
    {
        QsciLexer::setPaper(a0,a1);
        return;
    }

    extern void sipVH_Qsci_8(sip_gilstate_t,PyObject *,const QColor&,int);

    sipVH_Qsci_8(sipGILState,sipMeth,a0,a1);
}

bool sipQsciLexerSQL::readProperties(QSettings& a0,const QString& a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[23],sipPySelf,NULL,sipName_readProperties);

    if (!sipMeth)
        return QsciLexerSQL::readProperties(a0,a1);

    extern bool sipVH_Qsci_7(sip_gilstate_t,PyObject *,QSettings&,const QString&);

    return sipVH_Qsci_7(sipGILState,sipMeth,a0,a1);
}

bool sipQsciLexerSQL::writeProperties(QSettings& a0,const QString& a1) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[24]),sipPySelf,NULL,sipName_writeProperties);

    if (!sipMeth)
        return QsciLexerSQL::writeProperties(a0,a1);

    extern bool sipVH_Qsci_7(sip_gilstate_t,PyObject *,QSettings&,const QString&);

    return sipVH_Qsci_7(sipGILState,sipMeth,a0,a1);
}

bool sipQsciLexerSQL::event(QEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[25],sipPySelf,NULL,sipName_event);

    if (!sipMeth)
        return QObject::event(a0);

    typedef bool (*sipVH_QtCore_5)(sip_gilstate_t,PyObject *,QEvent *);

    return ((sipVH_QtCore_5)(sipModuleAPI_Qsci_QtCore->em_virthandlers[5]))(sipGILState,sipMeth,a0);
}

bool sipQsciLexerSQL::eventFilter(QObject *a0,QEvent *a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[26],sipPySelf,NULL,sipName_eventFilter);

    if (!sipMeth)
        return QObject::eventFilter(a0,a1);

    typedef bool (*sipVH_QtCore_18)(sip_gilstate_t,PyObject *,QObject *,QEvent *);

    return ((sipVH_QtCore_18)(sipModuleAPI_Qsci_QtCore->em_virthandlers[18]))(sipGILState,sipMeth,a0,a1);
}

void sipQsciLexerSQL::timerEvent(QTimerEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[27],sipPySelf,NULL,sipName_timerEvent);

    if (!sipMeth)
    {
        QObject::timerEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_9)(sip_gilstate_t,PyObject *,QTimerEvent *);

    ((sipVH_QtCore_9)(sipModuleAPI_Qsci_QtCore->em_virthandlers[9]))(sipGILState,sipMeth,a0);
}

void sipQsciLexerSQL::childEvent(QChildEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[28],sipPySelf,NULL,sipName_childEvent);

    if (!sipMeth)
    {
        QObject::childEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_25)(sip_gilstate_t,PyObject *,QChildEvent *);

    ((sipVH_QtCore_25)(sipModuleAPI_Qsci_QtCore->em_virthandlers[25]))(sipGILState,sipMeth,a0);
}

void sipQsciLexerSQL::customEvent(QEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[29],sipPySelf,NULL,sipName_customEvent);

    if (!sipMeth)
    {
        QObject::customEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_17)(sip_gilstate_t,PyObject *,QEvent *);

    ((sipVH_QtCore_17)(sipModuleAPI_Qsci_QtCore->em_virthandlers[17]))(sipGILState,sipMeth,a0);
}

void sipQsciLexerSQL::connectNotify(const char *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[30],sipPySelf,NULL,sipName_connectNotify);

    if (!sipMeth)
    {
        QObject::connectNotify(a0);
        return;
    }

    typedef void (*sipVH_QtCore_24)(sip_gilstate_t,PyObject *,const char *);

    ((sipVH_QtCore_24)(sipModuleAPI_Qsci_QtCore->em_virthandlers[24]))(sipGILState,sipMeth,a0);
}

void sipQsciLexerSQL::disconnectNotify(const char *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[31],sipPySelf,NULL,sipName_disconnectNotify);

    if (!sipMeth)
    {
        QObject::disconnectNotify(a0);
        return;
    }

    typedef void (*sipVH_QtCore_24)(sip_gilstate_t,PyObject *,const char *);

    ((sipVH_QtCore_24)(sipModuleAPI_Qsci_QtCore->em_virthandlers[24]))(sipGILState,sipMeth,a0);
}


PyDoc_STRVAR(doc_QsciLexerSQL_language, "QsciLexerSQL.language() -> str");

extern "C" {static PyObject *meth_QsciLexerSQL_language(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerSQL_language(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QsciLexerSQL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QsciLexerSQL, &sipCpp))
        {
            const char *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = (sipSelfWasArg ? sipCpp->QsciLexerSQL::language() : sipCpp->language());
            Py_END_ALLOW_THREADS

            if (sipRes == NULL)
            {
                Py_INCREF(Py_None);
                return Py_None;
            }

            return SIPBytes_FromString(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerSQL, sipName_language, doc_QsciLexerSQL_language);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerSQL_lexer, "QsciLexerSQL.lexer() -> str");

extern "C" {static PyObject *meth_QsciLexerSQL_lexer(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerSQL_lexer(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QsciLexerSQL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QsciLexerSQL, &sipCpp))
        {
            const char *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = (sipSelfWasArg ? sipCpp->QsciLexerSQL::lexer() : sipCpp->lexer());
            Py_END_ALLOW_THREADS

            if (sipRes == NULL)
            {
                Py_INCREF(Py_None);
                return Py_None;
            }

            return SIPBytes_FromString(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerSQL, sipName_lexer, doc_QsciLexerSQL_lexer);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerSQL_defaultColor, "QsciLexerSQL.defaultColor(int) -> QColor");

extern "C" {static PyObject *meth_QsciLexerSQL_defaultColor(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerSQL_defaultColor(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        int a0;
        QsciLexerSQL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QsciLexerSQL, &sipCpp, &a0))
        {
            QColor *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QColor((sipSelfWasArg ? sipCpp->QsciLexerSQL::defaultColor(a0) : sipCpp->defaultColor(a0)));
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QColor,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerSQL, sipName_defaultColor, doc_QsciLexerSQL_defaultColor);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerSQL_defaultEolFill, "QsciLexerSQL.defaultEolFill(int) -> bool");

extern "C" {static PyObject *meth_QsciLexerSQL_defaultEolFill(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerSQL_defaultEolFill(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        int a0;
        QsciLexerSQL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QsciLexerSQL, &sipCpp, &a0))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = (sipSelfWasArg ? sipCpp->QsciLexerSQL::defaultEolFill(a0) : sipCpp->defaultEolFill(a0));
            Py_END_ALLOW_THREADS

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerSQL, sipName_defaultEolFill, doc_QsciLexerSQL_defaultEolFill);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerSQL_defaultFont, "QsciLexerSQL.defaultFont(int) -> QFont");

extern "C" {static PyObject *meth_QsciLexerSQL_defaultFont(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerSQL_defaultFont(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        int a0;
        QsciLexerSQL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QsciLexerSQL, &sipCpp, &a0))
        {
            QFont *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QFont((sipSelfWasArg ? sipCpp->QsciLexerSQL::defaultFont(a0) : sipCpp->defaultFont(a0)));
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QFont,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerSQL, sipName_defaultFont, doc_QsciLexerSQL_defaultFont);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerSQL_defaultPaper, "QsciLexerSQL.defaultPaper(int) -> QColor");

extern "C" {static PyObject *meth_QsciLexerSQL_defaultPaper(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerSQL_defaultPaper(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        int a0;
        QsciLexerSQL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QsciLexerSQL, &sipCpp, &a0))
        {
            QColor *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QColor((sipSelfWasArg ? sipCpp->QsciLexerSQL::defaultPaper(a0) : sipCpp->defaultPaper(a0)));
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QColor,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerSQL, sipName_defaultPaper, doc_QsciLexerSQL_defaultPaper);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerSQL_keywords, "QsciLexerSQL.keywords(int) -> str");

extern "C" {static PyObject *meth_QsciLexerSQL_keywords(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerSQL_keywords(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        int a0;
        QsciLexerSQL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QsciLexerSQL, &sipCpp, &a0))
        {
            const char *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = (sipSelfWasArg ? sipCpp->QsciLexerSQL::keywords(a0) : sipCpp->keywords(a0));
            Py_END_ALLOW_THREADS

            if (sipRes == NULL)
            {
                Py_INCREF(Py_None);
                return Py_None;
            }

            return SIPBytes_FromString(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerSQL, sipName_keywords, doc_QsciLexerSQL_keywords);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerSQL_description, "QsciLexerSQL.description(int) -> QString");

extern "C" {static PyObject *meth_QsciLexerSQL_description(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerSQL_description(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        int a0;
        QsciLexerSQL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QsciLexerSQL, &sipCpp, &a0))
        {
            QString *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QString((sipSelfWasArg ? sipCpp->QsciLexerSQL::description(a0) : sipCpp->description(a0)));
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerSQL, sipName_description, doc_QsciLexerSQL_description);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerSQL_refreshProperties, "QsciLexerSQL.refreshProperties()");

extern "C" {static PyObject *meth_QsciLexerSQL_refreshProperties(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerSQL_refreshProperties(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QsciLexerSQL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QsciLexerSQL, &sipCpp))
        {
            Py_BEGIN_ALLOW_THREADS
            (sipSelfWasArg ? sipCpp->QsciLexerSQL::refreshProperties() : sipCpp->refreshProperties());
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerSQL, sipName_refreshProperties, doc_QsciLexerSQL_refreshProperties);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerSQL_backslashEscapes, "QsciLexerSQL.backslashEscapes() -> bool");

extern "C" {static PyObject *meth_QsciLexerSQL_backslashEscapes(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerSQL_backslashEscapes(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QsciLexerSQL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QsciLexerSQL, &sipCpp))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->backslashEscapes();
            Py_END_ALLOW_THREADS

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerSQL, sipName_backslashEscapes, doc_QsciLexerSQL_backslashEscapes);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerSQL_setDottedWords, "QsciLexerSQL.setDottedWords(bool)");

extern "C" {static PyObject *meth_QsciLexerSQL_setDottedWords(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerSQL_setDottedWords(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
        QsciLexerSQL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QsciLexerSQL, &sipCpp, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->setDottedWords(a0);
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerSQL, sipName_setDottedWords, doc_QsciLexerSQL_setDottedWords);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerSQL_dottedWords, "QsciLexerSQL.dottedWords() -> bool");

extern "C" {static PyObject *meth_QsciLexerSQL_dottedWords(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerSQL_dottedWords(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QsciLexerSQL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QsciLexerSQL, &sipCpp))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->dottedWords();
            Py_END_ALLOW_THREADS

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerSQL, sipName_dottedWords, doc_QsciLexerSQL_dottedWords);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerSQL_setFoldAtElse, "QsciLexerSQL.setFoldAtElse(bool)");

extern "C" {static PyObject *meth_QsciLexerSQL_setFoldAtElse(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerSQL_setFoldAtElse(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
        QsciLexerSQL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QsciLexerSQL, &sipCpp, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->setFoldAtElse(a0);
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerSQL, sipName_setFoldAtElse, doc_QsciLexerSQL_setFoldAtElse);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerSQL_foldAtElse, "QsciLexerSQL.foldAtElse() -> bool");

extern "C" {static PyObject *meth_QsciLexerSQL_foldAtElse(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerSQL_foldAtElse(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QsciLexerSQL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QsciLexerSQL, &sipCpp))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->foldAtElse();
            Py_END_ALLOW_THREADS

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerSQL, sipName_foldAtElse, doc_QsciLexerSQL_foldAtElse);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerSQL_foldComments, "QsciLexerSQL.foldComments() -> bool");

extern "C" {static PyObject *meth_QsciLexerSQL_foldComments(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerSQL_foldComments(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QsciLexerSQL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QsciLexerSQL, &sipCpp))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->foldComments();
            Py_END_ALLOW_THREADS

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerSQL, sipName_foldComments, doc_QsciLexerSQL_foldComments);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerSQL_foldCompact, "QsciLexerSQL.foldCompact() -> bool");

extern "C" {static PyObject *meth_QsciLexerSQL_foldCompact(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerSQL_foldCompact(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QsciLexerSQL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QsciLexerSQL, &sipCpp))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->foldCompact();
            Py_END_ALLOW_THREADS

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerSQL, sipName_foldCompact, doc_QsciLexerSQL_foldCompact);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerSQL_setFoldOnlyBegin, "QsciLexerSQL.setFoldOnlyBegin(bool)");

extern "C" {static PyObject *meth_QsciLexerSQL_setFoldOnlyBegin(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerSQL_setFoldOnlyBegin(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
        QsciLexerSQL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QsciLexerSQL, &sipCpp, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->setFoldOnlyBegin(a0);
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerSQL, sipName_setFoldOnlyBegin, doc_QsciLexerSQL_setFoldOnlyBegin);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerSQL_foldOnlyBegin, "QsciLexerSQL.foldOnlyBegin() -> bool");

extern "C" {static PyObject *meth_QsciLexerSQL_foldOnlyBegin(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerSQL_foldOnlyBegin(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QsciLexerSQL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QsciLexerSQL, &sipCpp))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->foldOnlyBegin();
            Py_END_ALLOW_THREADS

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerSQL, sipName_foldOnlyBegin, doc_QsciLexerSQL_foldOnlyBegin);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerSQL_setHashComments, "QsciLexerSQL.setHashComments(bool)");

extern "C" {static PyObject *meth_QsciLexerSQL_setHashComments(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerSQL_setHashComments(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
        QsciLexerSQL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QsciLexerSQL, &sipCpp, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->setHashComments(a0);
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerSQL, sipName_setHashComments, doc_QsciLexerSQL_setHashComments);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerSQL_hashComments, "QsciLexerSQL.hashComments() -> bool");

extern "C" {static PyObject *meth_QsciLexerSQL_hashComments(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerSQL_hashComments(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QsciLexerSQL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QsciLexerSQL, &sipCpp))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->hashComments();
            Py_END_ALLOW_THREADS

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerSQL, sipName_hashComments, doc_QsciLexerSQL_hashComments);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerSQL_setQuotedIdentifiers, "QsciLexerSQL.setQuotedIdentifiers(bool)");

extern "C" {static PyObject *meth_QsciLexerSQL_setQuotedIdentifiers(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerSQL_setQuotedIdentifiers(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
        QsciLexerSQL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QsciLexerSQL, &sipCpp, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->setQuotedIdentifiers(a0);
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerSQL, sipName_setQuotedIdentifiers, doc_QsciLexerSQL_setQuotedIdentifiers);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerSQL_quotedIdentifiers, "QsciLexerSQL.quotedIdentifiers() -> bool");

extern "C" {static PyObject *meth_QsciLexerSQL_quotedIdentifiers(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerSQL_quotedIdentifiers(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QsciLexerSQL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QsciLexerSQL, &sipCpp))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->quotedIdentifiers();
            Py_END_ALLOW_THREADS

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerSQL, sipName_quotedIdentifiers, doc_QsciLexerSQL_quotedIdentifiers);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerSQL_setBackslashEscapes, "QsciLexerSQL.setBackslashEscapes(bool)");

extern "C" {static PyObject *meth_QsciLexerSQL_setBackslashEscapes(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerSQL_setBackslashEscapes(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        bool a0;
        QsciLexerSQL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QsciLexerSQL, &sipCpp, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            (sipSelfWasArg ? sipCpp->QsciLexerSQL::setBackslashEscapes(a0) : sipCpp->setBackslashEscapes(a0));
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerSQL, sipName_setBackslashEscapes, doc_QsciLexerSQL_setBackslashEscapes);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerSQL_setFoldComments, "QsciLexerSQL.setFoldComments(bool)");

extern "C" {static PyObject *meth_QsciLexerSQL_setFoldComments(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerSQL_setFoldComments(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        bool a0;
        QsciLexerSQL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QsciLexerSQL, &sipCpp, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            (sipSelfWasArg ? sipCpp->QsciLexerSQL::setFoldComments(a0) : sipCpp->setFoldComments(a0));
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerSQL, sipName_setFoldComments, doc_QsciLexerSQL_setFoldComments);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerSQL_setFoldCompact, "QsciLexerSQL.setFoldCompact(bool)");

extern "C" {static PyObject *meth_QsciLexerSQL_setFoldCompact(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerSQL_setFoldCompact(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        bool a0;
        QsciLexerSQL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QsciLexerSQL, &sipCpp, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            (sipSelfWasArg ? sipCpp->QsciLexerSQL::setFoldCompact(a0) : sipCpp->setFoldCompact(a0));
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerSQL, sipName_setFoldCompact, doc_QsciLexerSQL_setFoldCompact);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerSQL_readProperties, "QsciLexerSQL.readProperties(QSettings, QString) -> bool");

extern "C" {static PyObject *meth_QsciLexerSQL_readProperties(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerSQL_readProperties(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QSettings * a0;
        const QString * a1;
        int a1State = 0;
        QsciLexerSQL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ9J1", &sipSelf, sipType_QsciLexerSQL, &sipCpp, sipType_QSettings, &a0, sipType_QString,&a1, &a1State))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = (sipSelfWasArg ? sipCpp->QsciLexerSQL::readProperties(*a0,*a1) : sipCpp->readProperties(*a0,*a1));
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast<QString *>(a1),sipType_QString,a1State);

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerSQL, sipName_readProperties, doc_QsciLexerSQL_readProperties);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerSQL_writeProperties, "QsciLexerSQL.writeProperties(QSettings, QString) -> bool");

extern "C" {static PyObject *meth_QsciLexerSQL_writeProperties(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerSQL_writeProperties(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QSettings * a0;
        const QString * a1;
        int a1State = 0;
        QsciLexerSQL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ9J1", &sipSelf, sipType_QsciLexerSQL, &sipCpp, sipType_QSettings, &a0, sipType_QString,&a1, &a1State))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = (sipSelfWasArg ? sipCpp->QsciLexerSQL::writeProperties(*a0,*a1) : sipCpp->writeProperties(*a0,*a1));
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast<QString *>(a1),sipType_QString,a1State);

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerSQL, sipName_writeProperties, doc_QsciLexerSQL_writeProperties);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QsciLexerSQL(void *, const sipTypeDef *);}
static void *cast_QsciLexerSQL(void *ptr, const sipTypeDef *targetType)
{
    void *res;

    if (targetType == sipType_QsciLexerSQL)
        return ptr;

    if ((res = ((const sipClassTypeDef *)sipType_QsciLexer)->ctd_cast((QsciLexer *)(QsciLexerSQL *)ptr,targetType)) != NULL)
        return res;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QsciLexerSQL(void *, int);}
static void release_QsciLexerSQL(void *sipCppV,int)
{
    Py_BEGIN_ALLOW_THREADS

    QsciLexerSQL *sipCpp = reinterpret_cast<QsciLexerSQL *>(sipCppV);

    if (QThread::currentThread() == sipCpp->thread())
        delete sipCpp;
    else
        sipCpp->deleteLater();

    Py_END_ALLOW_THREADS
}


extern "C" {static void dealloc_QsciLexerSQL(sipSimpleWrapper *);}
static void dealloc_QsciLexerSQL(sipSimpleWrapper *sipSelf)
{
    if (sipIsDerived(sipSelf))
        reinterpret_cast<sipQsciLexerSQL *>(sipGetAddress(sipSelf))->sipPySelf = NULL;

    if (sipIsPyOwned(sipSelf))
    {
        release_QsciLexerSQL(sipGetAddress(sipSelf),sipSelf->flags);
    }
}


extern "C" {static void *init_QsciLexerSQL(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_QsciLexerSQL(sipSimpleWrapper *sipSelf, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **sipOwner, PyObject **sipParseErr)
{
    sipQsciLexerSQL *sipCpp = 0;

    {
        QObject * a0 = 0;

        static const char *sipKwdList[] = {
            sipName_parent,
        };

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, sipKwdList, sipUnused, "|JH", sipType_QObject, &a0, sipOwner))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new sipQsciLexerSQL(a0);
            Py_END_ALLOW_THREADS

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    return NULL;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QsciLexerSQL[] = {{7, 255, 1}};


static PyMethodDef methods_QsciLexerSQL[] = {
    {SIP_MLNAME_CAST(sipName_backslashEscapes), meth_QsciLexerSQL_backslashEscapes, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerSQL_backslashEscapes)},
    {SIP_MLNAME_CAST(sipName_defaultColor), meth_QsciLexerSQL_defaultColor, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerSQL_defaultColor)},
    {SIP_MLNAME_CAST(sipName_defaultEolFill), meth_QsciLexerSQL_defaultEolFill, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerSQL_defaultEolFill)},
    {SIP_MLNAME_CAST(sipName_defaultFont), meth_QsciLexerSQL_defaultFont, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerSQL_defaultFont)},
    {SIP_MLNAME_CAST(sipName_defaultPaper), meth_QsciLexerSQL_defaultPaper, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerSQL_defaultPaper)},
    {SIP_MLNAME_CAST(sipName_description), meth_QsciLexerSQL_description, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerSQL_description)},
    {SIP_MLNAME_CAST(sipName_dottedWords), meth_QsciLexerSQL_dottedWords, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerSQL_dottedWords)},
    {SIP_MLNAME_CAST(sipName_foldAtElse), meth_QsciLexerSQL_foldAtElse, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerSQL_foldAtElse)},
    {SIP_MLNAME_CAST(sipName_foldComments), meth_QsciLexerSQL_foldComments, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerSQL_foldComments)},
    {SIP_MLNAME_CAST(sipName_foldCompact), meth_QsciLexerSQL_foldCompact, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerSQL_foldCompact)},
    {SIP_MLNAME_CAST(sipName_foldOnlyBegin), meth_QsciLexerSQL_foldOnlyBegin, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerSQL_foldOnlyBegin)},
    {SIP_MLNAME_CAST(sipName_hashComments), meth_QsciLexerSQL_hashComments, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerSQL_hashComments)},
    {SIP_MLNAME_CAST(sipName_keywords), meth_QsciLexerSQL_keywords, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerSQL_keywords)},
    {SIP_MLNAME_CAST(sipName_language), meth_QsciLexerSQL_language, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerSQL_language)},
    {SIP_MLNAME_CAST(sipName_lexer), meth_QsciLexerSQL_lexer, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerSQL_lexer)},
    {SIP_MLNAME_CAST(sipName_quotedIdentifiers), meth_QsciLexerSQL_quotedIdentifiers, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerSQL_quotedIdentifiers)},
    {SIP_MLNAME_CAST(sipName_readProperties), meth_QsciLexerSQL_readProperties, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerSQL_readProperties)},
    {SIP_MLNAME_CAST(sipName_refreshProperties), meth_QsciLexerSQL_refreshProperties, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerSQL_refreshProperties)},
    {SIP_MLNAME_CAST(sipName_setBackslashEscapes), meth_QsciLexerSQL_setBackslashEscapes, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerSQL_setBackslashEscapes)},
    {SIP_MLNAME_CAST(sipName_setDottedWords), meth_QsciLexerSQL_setDottedWords, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerSQL_setDottedWords)},
    {SIP_MLNAME_CAST(sipName_setFoldAtElse), meth_QsciLexerSQL_setFoldAtElse, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerSQL_setFoldAtElse)},
    {SIP_MLNAME_CAST(sipName_setFoldComments), meth_QsciLexerSQL_setFoldComments, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerSQL_setFoldComments)},
    {SIP_MLNAME_CAST(sipName_setFoldCompact), meth_QsciLexerSQL_setFoldCompact, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerSQL_setFoldCompact)},
    {SIP_MLNAME_CAST(sipName_setFoldOnlyBegin), meth_QsciLexerSQL_setFoldOnlyBegin, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerSQL_setFoldOnlyBegin)},
    {SIP_MLNAME_CAST(sipName_setHashComments), meth_QsciLexerSQL_setHashComments, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerSQL_setHashComments)},
    {SIP_MLNAME_CAST(sipName_setQuotedIdentifiers), meth_QsciLexerSQL_setQuotedIdentifiers, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerSQL_setQuotedIdentifiers)},
    {SIP_MLNAME_CAST(sipName_writeProperties), meth_QsciLexerSQL_writeProperties, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerSQL_writeProperties)}
};

static sipEnumMemberDef enummembers_QsciLexerSQL[] = {
    {sipName_Comment, QsciLexerSQL::Comment, -1},
    {sipName_CommentDoc, QsciLexerSQL::CommentDoc, -1},
    {sipName_CommentDocKeyword, QsciLexerSQL::CommentDocKeyword, -1},
    {sipName_CommentDocKeywordError, QsciLexerSQL::CommentDocKeywordError, -1},
    {sipName_CommentLine, QsciLexerSQL::CommentLine, -1},
    {sipName_CommentLineHash, QsciLexerSQL::CommentLineHash, -1},
    {sipName_Default, QsciLexerSQL::Default, -1},
    {sipName_DoubleQuotedString, QsciLexerSQL::DoubleQuotedString, -1},
    {sipName_Identifier, QsciLexerSQL::Identifier, -1},
    {sipName_Keyword, QsciLexerSQL::Keyword, -1},
    {sipName_KeywordSet5, QsciLexerSQL::KeywordSet5, -1},
    {sipName_KeywordSet6, QsciLexerSQL::KeywordSet6, -1},
    {sipName_KeywordSet7, QsciLexerSQL::KeywordSet7, -1},
    {sipName_KeywordSet8, QsciLexerSQL::KeywordSet8, -1},
    {sipName_Number, QsciLexerSQL::Number, -1},
    {sipName_Operator, QsciLexerSQL::Operator, -1},
    {sipName_PlusComment, QsciLexerSQL::PlusComment, -1},
    {sipName_PlusKeyword, QsciLexerSQL::PlusKeyword, -1},
    {sipName_PlusPrompt, QsciLexerSQL::PlusPrompt, -1},
    {sipName_QuotedIdentifier, QsciLexerSQL::QuotedIdentifier, -1},
    {sipName_SingleQuotedString, QsciLexerSQL::SingleQuotedString, -1},
};

PyDoc_STRVAR(doc_QsciLexerSQL, "\1QsciLexerSQL(QObject parent=None)");


pyqt4ClassTypeDef sipTypeDef_Qsci_QsciLexerSQL = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_SCC|SIP_TYPE_CLASS,
        sipNameNr_QsciLexerSQL,
        {0}
    },
    {
        sipNameNr_QsciLexerSQL,
        {0, 0, 1},
        27, methods_QsciLexerSQL,
        21, enummembers_QsciLexerSQL,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    doc_QsciLexerSQL,
    -1,
    -1,
    supers_QsciLexerSQL,
    0,
    init_QsciLexerSQL,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QsciLexerSQL,
    0,
    0,
    0,
    release_QsciLexerSQL,
    cast_QsciLexerSQL,
    0,
    0,
    0
},
    &QsciLexerSQL::staticMetaObject,
    0,
    0
};
