/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.12.5-snapshot-c2987628087f on Thu Sep  1 02:20:43 2011
 *
 * Copyright (c) 2011 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of QScintilla.
 * 
 * This file may be used under the terms of the GNU General Public
 * License versions 2.0 or 3.0 as published by the Free Software
 * Foundation and appearing in the files LICENSE.GPL2 and LICENSE.GPL3
 * included in the packaging of this file.  Alternatively you may (at
 * your option) use any later version of the GNU General Public
 * License if such license has been publicly approved by Riverbank
 * Computing Limited (or its successors, if any) and the KDE Free Qt
 * Foundation. In addition, as a special exception, Riverbank gives you
 * certain additional rights. These rights are described in the Riverbank
 * GPL Exception version 1.1, which can be found in the file
 * GPL_EXCEPTION.txt in this package.
 * 
 * Please review the following information to ensure GNU General
 * Public Licensing requirements will be met:
 * http://trolltech.com/products/qt/licenses/licensing/opensource/. If
 * you are unsure which license is appropriate for your use, please
 * review the following information:
 * http://trolltech.com/products/qt/licenses/licensing/licensingoverview
 * or contact the sales department at sales@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQsci.h"

#line 34 "sip/qscilexerpov.sip"
#include <Qsci/qscilexerpov.h>
#line 39 "./sipQsciQsciLexerPOV.cpp"

#line 39 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qobject.sip"
#include <qobject.h>
#line 43 "./sipQsciQsciLexerPOV.cpp"
#line 36 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qsettings.sip"
#include <qsettings.h>
#line 46 "./sipQsciQsciLexerPOV.cpp"
#line 41 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qstring.sip"
#include <qstring.h>
#line 49 "./sipQsciQsciLexerPOV.cpp"
#line 40 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtGui/qcolor.sip"
#include <qcolor.h>
#line 52 "./sipQsciQsciLexerPOV.cpp"
#line 40 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtGui/qfont.sip"
#include <qfont.h>
#line 55 "./sipQsciQsciLexerPOV.cpp"
#line 34 "sip/qsciabstractapis.sip"
#include <Qsci/qsciabstractapis.h>
#line 58 "./sipQsciQsciLexerPOV.cpp"
#line 34 "sip/qsciscintilla.sip"
#include <Qsci/qsciscintilla.h>
#line 61 "./sipQsciQsciLexerPOV.cpp"
#line 36 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 64 "./sipQsciQsciLexerPOV.cpp"
#line 315 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 67 "./sipQsciQsciLexerPOV.cpp"
#line 303 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 70 "./sipQsciQsciLexerPOV.cpp"
#line 243 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qvariant.sip"
#include <qvariant.h>
#line 73 "./sipQsciQsciLexerPOV.cpp"
#line 38 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qlist.sip"
#include <qlist.h>
#line 76 "./sipQsciQsciLexerPOV.cpp"
#line 42 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qbytearray.sip"
#include <qbytearray.h>
#line 79 "./sipQsciQsciLexerPOV.cpp"
#line 40 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 82 "./sipQsciQsciLexerPOV.cpp"
#line 125 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qlist.sip"
#include <qlist.h>
#line 85 "./sipQsciQsciLexerPOV.cpp"
#line 36 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qthread.sip"
#include <qthread.h>
#line 88 "./sipQsciQsciLexerPOV.cpp"
#line 40 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qregexp.sip"
#include <qregexp.h>
#line 91 "./sipQsciQsciLexerPOV.cpp"
#line 36 "/System/Library/Frameworks/Python.framework/Versions/2.7/share/sip/PyQt4/QtCore/qobjectdefs.sip"
#include <qobjectdefs.h>
#line 94 "./sipQsciQsciLexerPOV.cpp"


class sipQsciLexerPOV : public QsciLexerPOV
{
public:
    sipQsciLexerPOV(QObject *);
    virtual ~sipQsciLexerPOV();

    int qt_metacall(QMetaObject::Call,int,void **);
    void *qt_metacast(const char *);
    const QMetaObject *metaObject() const;

    /*
     * There is a protected method for every virtual method visible from
     * this class.
     */
protected:
    void setFoldComments(bool);
    void setFoldCompact(bool);
    void setFoldDirectives(bool);
    const char * language() const;
    const char * lexer() const;
    int lexerId() const;
    QColor color(int) const;
    bool eolFill(int) const;
    QFont font(int) const;
    const char * keywords(int) const;
    QString description(int) const;
    QColor paper(int) const;
    QColor defaultColor(int) const;
    bool defaultEolFill(int) const;
    QFont defaultFont(int) const;
    QColor defaultPaper(int) const;
    void refreshProperties();
    int styleBitsNeeded() const;
    void setAutoIndentStyle(int);
    void setColor(const QColor&,int);
    void setEolFill(bool,int);
    void setFont(const QFont&,int);
    void setPaper(const QColor&,int);
    bool readProperties(QSettings&,const QString&);
    bool writeProperties(QSettings&,const QString&) const;
    bool event(QEvent *);
    bool eventFilter(QObject *,QEvent *);
    void timerEvent(QTimerEvent *);
    void childEvent(QChildEvent *);
    void customEvent(QEvent *);
    void connectNotify(const char *);
    void disconnectNotify(const char *);

public:
    sipSimpleWrapper *sipPySelf;

private:
    sipQsciLexerPOV(const sipQsciLexerPOV &);
    sipQsciLexerPOV &operator = (const sipQsciLexerPOV &);

    char sipPyMethods[32];
};

sipQsciLexerPOV::sipQsciLexerPOV(QObject *a0): QsciLexerPOV(a0), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipQsciLexerPOV::~sipQsciLexerPOV()
{
    sipCommonDtor(sipPySelf);
}

const QMetaObject *sipQsciLexerPOV::metaObject() const
{
    return sip_Qsci_qt_metaobject(sipPySelf,sipType_QsciLexerPOV);
}

int sipQsciLexerPOV::qt_metacall(QMetaObject::Call _c,int _id,void **_a)
{
    _id = QsciLexerPOV::qt_metacall(_c,_id,_a);

    if (_id >= 0)
        _id = sip_Qsci_qt_metacall(sipPySelf,sipType_QsciLexerPOV,_c,_id,_a);

    return _id;
}

void *sipQsciLexerPOV::qt_metacast(const char *_clname)
{
    return (sip_Qsci_qt_metacast && sip_Qsci_qt_metacast(sipPySelf,sipType_QsciLexerPOV,_clname)) ? this : QsciLexerPOV::qt_metacast(_clname);
}

void sipQsciLexerPOV::setFoldComments(bool a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[0],sipPySelf,NULL,sipName_setFoldComments);

    if (!sipMeth)
    {
        QsciLexerPOV::setFoldComments(a0);
        return;
    }

    typedef void (*sipVH_QtGui_6)(sip_gilstate_t,PyObject *,bool);

    ((sipVH_QtGui_6)(sipModuleAPI_Qsci_QtGui->em_virthandlers[6]))(sipGILState,sipMeth,a0);
}

void sipQsciLexerPOV::setFoldCompact(bool a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[1],sipPySelf,NULL,sipName_setFoldCompact);

    if (!sipMeth)
    {
        QsciLexerPOV::setFoldCompact(a0);
        return;
    }

    typedef void (*sipVH_QtGui_6)(sip_gilstate_t,PyObject *,bool);

    ((sipVH_QtGui_6)(sipModuleAPI_Qsci_QtGui->em_virthandlers[6]))(sipGILState,sipMeth,a0);
}

void sipQsciLexerPOV::setFoldDirectives(bool a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[2],sipPySelf,NULL,sipName_setFoldDirectives);

    if (!sipMeth)
    {
        QsciLexerPOV::setFoldDirectives(a0);
        return;
    }

    typedef void (*sipVH_QtGui_6)(sip_gilstate_t,PyObject *,bool);

    ((sipVH_QtGui_6)(sipModuleAPI_Qsci_QtGui->em_virthandlers[6]))(sipGILState,sipMeth,a0);
}

const char * sipQsciLexerPOV::language() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[3]),sipPySelf,NULL,sipName_language);

    if (!sipMeth)
        return QsciLexerPOV::language();

    extern const char * sipVH_Qsci_13(sip_gilstate_t,PyObject *,int,sipSimpleWrapper *);

    return sipVH_Qsci_13(sipGILState,sipMeth,-35,sipPySelf);
}

const char * sipQsciLexerPOV::lexer() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[4]),sipPySelf,NULL,sipName_lexer);

    if (!sipMeth)
        return QsciLexerPOV::lexer();

    extern const char * sipVH_Qsci_13(sip_gilstate_t,PyObject *,int,sipSimpleWrapper *);

    return sipVH_Qsci_13(sipGILState,sipMeth,-36,sipPySelf);
}

int sipQsciLexerPOV::lexerId() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[5]),sipPySelf,NULL,sipName_lexerId);

    if (!sipMeth)
        return QsciLexer::lexerId();

    typedef int (*sipVH_QtCore_6)(sip_gilstate_t,PyObject *);

    return ((sipVH_QtCore_6)(sipModuleAPI_Qsci_QtCore->em_virthandlers[6]))(sipGILState,sipMeth);
}

QColor sipQsciLexerPOV::color(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[6]),sipPySelf,NULL,sipName_color);

    if (!sipMeth)
        return QsciLexer::color(a0);

    extern QColor sipVH_Qsci_11(sip_gilstate_t,PyObject *,int);

    return sipVH_Qsci_11(sipGILState,sipMeth,a0);
}

bool sipQsciLexerPOV::eolFill(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[7]),sipPySelf,NULL,sipName_eolFill);

    if (!sipMeth)
        return QsciLexer::eolFill(a0);

    typedef bool (*sipVH_QtCore_23)(sip_gilstate_t,PyObject *,int);

    return ((sipVH_QtCore_23)(sipModuleAPI_Qsci_QtCore->em_virthandlers[23]))(sipGILState,sipMeth,a0);
}

QFont sipQsciLexerPOV::font(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[8]),sipPySelf,NULL,sipName_font);

    if (!sipMeth)
        return QsciLexer::font(a0);

    extern QFont sipVH_Qsci_12(sip_gilstate_t,PyObject *,int);

    return sipVH_Qsci_12(sipGILState,sipMeth,a0);
}

const char * sipQsciLexerPOV::keywords(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[9]),sipPySelf,NULL,sipName_keywords);

    if (!sipMeth)
        return QsciLexerPOV::keywords(a0);

    typedef const char * (*sipVH_QtGui_146)(sip_gilstate_t,PyObject *,int,int,sipSimpleWrapper *);

    return ((sipVH_QtGui_146)(sipModuleAPI_Qsci_QtGui->em_virthandlers[146]))(sipGILState,sipMeth,a0,-37,sipPySelf);
}

QString sipQsciLexerPOV::description(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[10]),sipPySelf,NULL,sipName_description);

    if (!sipMeth)
        return QsciLexerPOV::description(a0);

    typedef QString (*sipVH_QtGui_111)(sip_gilstate_t,PyObject *,int);

    return ((sipVH_QtGui_111)(sipModuleAPI_Qsci_QtGui->em_virthandlers[111]))(sipGILState,sipMeth,a0);
}

QColor sipQsciLexerPOV::paper(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[11]),sipPySelf,NULL,sipName_paper);

    if (!sipMeth)
        return QsciLexer::paper(a0);

    extern QColor sipVH_Qsci_11(sip_gilstate_t,PyObject *,int);

    return sipVH_Qsci_11(sipGILState,sipMeth,a0);
}

QColor sipQsciLexerPOV::defaultColor(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[12]),sipPySelf,NULL,sipName_defaultColor);

    if (!sipMeth)
        return QsciLexerPOV::defaultColor(a0);

    extern QColor sipVH_Qsci_11(sip_gilstate_t,PyObject *,int);

    return sipVH_Qsci_11(sipGILState,sipMeth,a0);
}

bool sipQsciLexerPOV::defaultEolFill(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[13]),sipPySelf,NULL,sipName_defaultEolFill);

    if (!sipMeth)
        return QsciLexerPOV::defaultEolFill(a0);

    typedef bool (*sipVH_QtCore_23)(sip_gilstate_t,PyObject *,int);

    return ((sipVH_QtCore_23)(sipModuleAPI_Qsci_QtCore->em_virthandlers[23]))(sipGILState,sipMeth,a0);
}

QFont sipQsciLexerPOV::defaultFont(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[14]),sipPySelf,NULL,sipName_defaultFont);

    if (!sipMeth)
        return QsciLexerPOV::defaultFont(a0);

    extern QFont sipVH_Qsci_12(sip_gilstate_t,PyObject *,int);

    return sipVH_Qsci_12(sipGILState,sipMeth,a0);
}

QColor sipQsciLexerPOV::defaultPaper(int a0) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[15]),sipPySelf,NULL,sipName_defaultPaper);

    if (!sipMeth)
        return QsciLexerPOV::defaultPaper(a0);

    extern QColor sipVH_Qsci_11(sip_gilstate_t,PyObject *,int);

    return sipVH_Qsci_11(sipGILState,sipMeth,a0);
}

void sipQsciLexerPOV::refreshProperties()
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[16],sipPySelf,NULL,sipName_refreshProperties);

    if (!sipMeth)
    {
        QsciLexerPOV::refreshProperties();
        return;
    }

    typedef void (*sipVH_QtCore_11)(sip_gilstate_t,PyObject *);

    ((sipVH_QtCore_11)(sipModuleAPI_Qsci_QtCore->em_virthandlers[11]))(sipGILState,sipMeth);
}

int sipQsciLexerPOV::styleBitsNeeded() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[17]),sipPySelf,NULL,sipName_styleBitsNeeded);

    if (!sipMeth)
        return QsciLexer::styleBitsNeeded();

    typedef int (*sipVH_QtCore_6)(sip_gilstate_t,PyObject *);

    return ((sipVH_QtCore_6)(sipModuleAPI_Qsci_QtCore->em_virthandlers[6]))(sipGILState,sipMeth);
}

void sipQsciLexerPOV::setAutoIndentStyle(int a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[18],sipPySelf,NULL,sipName_setAutoIndentStyle);

    if (!sipMeth)
    {
        QsciLexer::setAutoIndentStyle(a0);
        return;
    }

    typedef void (*sipVH_QtCore_4)(sip_gilstate_t,PyObject *,int);

    ((sipVH_QtCore_4)(sipModuleAPI_Qsci_QtCore->em_virthandlers[4]))(sipGILState,sipMeth,a0);
}

void sipQsciLexerPOV::setColor(const QColor& a0,int a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[19],sipPySelf,NULL,sipName_setColor);

    if (!sipMeth)
    {
        QsciLexer::setColor(a0,a1);
        return;
    }

    extern void sipVH_Qsci_8(sip_gilstate_t,PyObject *,const QColor&,int);

    sipVH_Qsci_8(sipGILState,sipMeth,a0,a1);
}

void sipQsciLexerPOV::setEolFill(bool a0,int a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[20],sipPySelf,NULL,sipName_setEolFill);

    if (!sipMeth)
    {
        QsciLexer::setEolFill(a0,a1);
        return;
    }

    extern void sipVH_Qsci_10(sip_gilstate_t,PyObject *,bool,int);

    sipVH_Qsci_10(sipGILState,sipMeth,a0,a1);
}

void sipQsciLexerPOV::setFont(const QFont& a0,int a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[21],sipPySelf,NULL,sipName_setFont);

    if (!sipMeth)
    {
        QsciLexer::setFont(a0,a1);
        return;
    }

    extern void sipVH_Qsci_9(sip_gilstate_t,PyObject *,const QFont&,int);

    sipVH_Qsci_9(sipGILState,sipMeth,a0,a1);
}

void sipQsciLexerPOV::setPaper(const QColor& a0,int a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[22],sipPySelf,NULL,sipName_setPaper);

    if (!sipMeth)
    {
        QsciLexer::setPaper(a0,a1);
        return;
    }

    extern void sipVH_Qsci_8(sip_gilstate_t,PyObject *,const QColor&,int);

    sipVH_Qsci_8(sipGILState,sipMeth,a0,a1);
}

bool sipQsciLexerPOV::readProperties(QSettings& a0,const QString& a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[23],sipPySelf,NULL,sipName_readProperties);

    if (!sipMeth)
        return QsciLexerPOV::readProperties(a0,a1);

    extern bool sipVH_Qsci_7(sip_gilstate_t,PyObject *,QSettings&,const QString&);

    return sipVH_Qsci_7(sipGILState,sipMeth,a0,a1);
}

bool sipQsciLexerPOV::writeProperties(QSettings& a0,const QString& a1) const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[24]),sipPySelf,NULL,sipName_writeProperties);

    if (!sipMeth)
        return QsciLexerPOV::writeProperties(a0,a1);

    extern bool sipVH_Qsci_7(sip_gilstate_t,PyObject *,QSettings&,const QString&);

    return sipVH_Qsci_7(sipGILState,sipMeth,a0,a1);
}

bool sipQsciLexerPOV::event(QEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[25],sipPySelf,NULL,sipName_event);

    if (!sipMeth)
        return QObject::event(a0);

    typedef bool (*sipVH_QtCore_5)(sip_gilstate_t,PyObject *,QEvent *);

    return ((sipVH_QtCore_5)(sipModuleAPI_Qsci_QtCore->em_virthandlers[5]))(sipGILState,sipMeth,a0);
}

bool sipQsciLexerPOV::eventFilter(QObject *a0,QEvent *a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[26],sipPySelf,NULL,sipName_eventFilter);

    if (!sipMeth)
        return QObject::eventFilter(a0,a1);

    typedef bool (*sipVH_QtCore_18)(sip_gilstate_t,PyObject *,QObject *,QEvent *);

    return ((sipVH_QtCore_18)(sipModuleAPI_Qsci_QtCore->em_virthandlers[18]))(sipGILState,sipMeth,a0,a1);
}

void sipQsciLexerPOV::timerEvent(QTimerEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[27],sipPySelf,NULL,sipName_timerEvent);

    if (!sipMeth)
    {
        QObject::timerEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_9)(sip_gilstate_t,PyObject *,QTimerEvent *);

    ((sipVH_QtCore_9)(sipModuleAPI_Qsci_QtCore->em_virthandlers[9]))(sipGILState,sipMeth,a0);
}

void sipQsciLexerPOV::childEvent(QChildEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[28],sipPySelf,NULL,sipName_childEvent);

    if (!sipMeth)
    {
        QObject::childEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_25)(sip_gilstate_t,PyObject *,QChildEvent *);

    ((sipVH_QtCore_25)(sipModuleAPI_Qsci_QtCore->em_virthandlers[25]))(sipGILState,sipMeth,a0);
}

void sipQsciLexerPOV::customEvent(QEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[29],sipPySelf,NULL,sipName_customEvent);

    if (!sipMeth)
    {
        QObject::customEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_17)(sip_gilstate_t,PyObject *,QEvent *);

    ((sipVH_QtCore_17)(sipModuleAPI_Qsci_QtCore->em_virthandlers[17]))(sipGILState,sipMeth,a0);
}

void sipQsciLexerPOV::connectNotify(const char *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[30],sipPySelf,NULL,sipName_connectNotify);

    if (!sipMeth)
    {
        QObject::connectNotify(a0);
        return;
    }

    typedef void (*sipVH_QtCore_24)(sip_gilstate_t,PyObject *,const char *);

    ((sipVH_QtCore_24)(sipModuleAPI_Qsci_QtCore->em_virthandlers[24]))(sipGILState,sipMeth,a0);
}

void sipQsciLexerPOV::disconnectNotify(const char *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[31],sipPySelf,NULL,sipName_disconnectNotify);

    if (!sipMeth)
    {
        QObject::disconnectNotify(a0);
        return;
    }

    typedef void (*sipVH_QtCore_24)(sip_gilstate_t,PyObject *,const char *);

    ((sipVH_QtCore_24)(sipModuleAPI_Qsci_QtCore->em_virthandlers[24]))(sipGILState,sipMeth,a0);
}


PyDoc_STRVAR(doc_QsciLexerPOV_language, "QsciLexerPOV.language() -> str");

extern "C" {static PyObject *meth_QsciLexerPOV_language(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerPOV_language(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QsciLexerPOV *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QsciLexerPOV, &sipCpp))
        {
            const char *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = (sipSelfWasArg ? sipCpp->QsciLexerPOV::language() : sipCpp->language());
            Py_END_ALLOW_THREADS

            if (sipRes == NULL)
            {
                Py_INCREF(Py_None);
                return Py_None;
            }

            return SIPBytes_FromString(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerPOV, sipName_language, doc_QsciLexerPOV_language);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerPOV_lexer, "QsciLexerPOV.lexer() -> str");

extern "C" {static PyObject *meth_QsciLexerPOV_lexer(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerPOV_lexer(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QsciLexerPOV *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QsciLexerPOV, &sipCpp))
        {
            const char *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = (sipSelfWasArg ? sipCpp->QsciLexerPOV::lexer() : sipCpp->lexer());
            Py_END_ALLOW_THREADS

            if (sipRes == NULL)
            {
                Py_INCREF(Py_None);
                return Py_None;
            }

            return SIPBytes_FromString(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerPOV, sipName_lexer, doc_QsciLexerPOV_lexer);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerPOV_defaultColor, "QsciLexerPOV.defaultColor(int) -> QColor");

extern "C" {static PyObject *meth_QsciLexerPOV_defaultColor(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerPOV_defaultColor(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        int a0;
        QsciLexerPOV *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QsciLexerPOV, &sipCpp, &a0))
        {
            QColor *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QColor((sipSelfWasArg ? sipCpp->QsciLexerPOV::defaultColor(a0) : sipCpp->defaultColor(a0)));
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QColor,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerPOV, sipName_defaultColor, doc_QsciLexerPOV_defaultColor);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerPOV_defaultEolFill, "QsciLexerPOV.defaultEolFill(int) -> bool");

extern "C" {static PyObject *meth_QsciLexerPOV_defaultEolFill(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerPOV_defaultEolFill(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        int a0;
        QsciLexerPOV *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QsciLexerPOV, &sipCpp, &a0))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = (sipSelfWasArg ? sipCpp->QsciLexerPOV::defaultEolFill(a0) : sipCpp->defaultEolFill(a0));
            Py_END_ALLOW_THREADS

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerPOV, sipName_defaultEolFill, doc_QsciLexerPOV_defaultEolFill);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerPOV_defaultFont, "QsciLexerPOV.defaultFont(int) -> QFont");

extern "C" {static PyObject *meth_QsciLexerPOV_defaultFont(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerPOV_defaultFont(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        int a0;
        QsciLexerPOV *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QsciLexerPOV, &sipCpp, &a0))
        {
            QFont *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QFont((sipSelfWasArg ? sipCpp->QsciLexerPOV::defaultFont(a0) : sipCpp->defaultFont(a0)));
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QFont,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerPOV, sipName_defaultFont, doc_QsciLexerPOV_defaultFont);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerPOV_defaultPaper, "QsciLexerPOV.defaultPaper(int) -> QColor");

extern "C" {static PyObject *meth_QsciLexerPOV_defaultPaper(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerPOV_defaultPaper(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        int a0;
        QsciLexerPOV *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QsciLexerPOV, &sipCpp, &a0))
        {
            QColor *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QColor((sipSelfWasArg ? sipCpp->QsciLexerPOV::defaultPaper(a0) : sipCpp->defaultPaper(a0)));
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QColor,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerPOV, sipName_defaultPaper, doc_QsciLexerPOV_defaultPaper);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerPOV_keywords, "QsciLexerPOV.keywords(int) -> str");

extern "C" {static PyObject *meth_QsciLexerPOV_keywords(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerPOV_keywords(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        int a0;
        QsciLexerPOV *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QsciLexerPOV, &sipCpp, &a0))
        {
            const char *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = (sipSelfWasArg ? sipCpp->QsciLexerPOV::keywords(a0) : sipCpp->keywords(a0));
            Py_END_ALLOW_THREADS

            if (sipRes == NULL)
            {
                Py_INCREF(Py_None);
                return Py_None;
            }

            return SIPBytes_FromString(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerPOV, sipName_keywords, doc_QsciLexerPOV_keywords);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerPOV_description, "QsciLexerPOV.description(int) -> QString");

extern "C" {static PyObject *meth_QsciLexerPOV_description(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerPOV_description(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        int a0;
        QsciLexerPOV *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bi", &sipSelf, sipType_QsciLexerPOV, &sipCpp, &a0))
        {
            QString *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QString((sipSelfWasArg ? sipCpp->QsciLexerPOV::description(a0) : sipCpp->description(a0)));
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerPOV, sipName_description, doc_QsciLexerPOV_description);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerPOV_refreshProperties, "QsciLexerPOV.refreshProperties()");

extern "C" {static PyObject *meth_QsciLexerPOV_refreshProperties(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerPOV_refreshProperties(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QsciLexerPOV *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QsciLexerPOV, &sipCpp))
        {
            Py_BEGIN_ALLOW_THREADS
            (sipSelfWasArg ? sipCpp->QsciLexerPOV::refreshProperties() : sipCpp->refreshProperties());
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerPOV, sipName_refreshProperties, doc_QsciLexerPOV_refreshProperties);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerPOV_foldComments, "QsciLexerPOV.foldComments() -> bool");

extern "C" {static PyObject *meth_QsciLexerPOV_foldComments(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerPOV_foldComments(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QsciLexerPOV *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QsciLexerPOV, &sipCpp))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->foldComments();
            Py_END_ALLOW_THREADS

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerPOV, sipName_foldComments, doc_QsciLexerPOV_foldComments);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerPOV_foldCompact, "QsciLexerPOV.foldCompact() -> bool");

extern "C" {static PyObject *meth_QsciLexerPOV_foldCompact(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerPOV_foldCompact(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QsciLexerPOV *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QsciLexerPOV, &sipCpp))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->foldCompact();
            Py_END_ALLOW_THREADS

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerPOV, sipName_foldCompact, doc_QsciLexerPOV_foldCompact);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerPOV_foldDirectives, "QsciLexerPOV.foldDirectives() -> bool");

extern "C" {static PyObject *meth_QsciLexerPOV_foldDirectives(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerPOV_foldDirectives(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QsciLexerPOV *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QsciLexerPOV, &sipCpp))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->foldDirectives();
            Py_END_ALLOW_THREADS

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerPOV, sipName_foldDirectives, doc_QsciLexerPOV_foldDirectives);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerPOV_setFoldComments, "QsciLexerPOV.setFoldComments(bool)");

extern "C" {static PyObject *meth_QsciLexerPOV_setFoldComments(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerPOV_setFoldComments(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        bool a0;
        QsciLexerPOV *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QsciLexerPOV, &sipCpp, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            (sipSelfWasArg ? sipCpp->QsciLexerPOV::setFoldComments(a0) : sipCpp->setFoldComments(a0));
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerPOV, sipName_setFoldComments, doc_QsciLexerPOV_setFoldComments);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerPOV_setFoldCompact, "QsciLexerPOV.setFoldCompact(bool)");

extern "C" {static PyObject *meth_QsciLexerPOV_setFoldCompact(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerPOV_setFoldCompact(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        bool a0;
        QsciLexerPOV *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QsciLexerPOV, &sipCpp, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            (sipSelfWasArg ? sipCpp->QsciLexerPOV::setFoldCompact(a0) : sipCpp->setFoldCompact(a0));
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerPOV, sipName_setFoldCompact, doc_QsciLexerPOV_setFoldCompact);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerPOV_setFoldDirectives, "QsciLexerPOV.setFoldDirectives(bool)");

extern "C" {static PyObject *meth_QsciLexerPOV_setFoldDirectives(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerPOV_setFoldDirectives(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        bool a0;
        QsciLexerPOV *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QsciLexerPOV, &sipCpp, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            (sipSelfWasArg ? sipCpp->QsciLexerPOV::setFoldDirectives(a0) : sipCpp->setFoldDirectives(a0));
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerPOV, sipName_setFoldDirectives, doc_QsciLexerPOV_setFoldDirectives);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerPOV_readProperties, "QsciLexerPOV.readProperties(QSettings, QString) -> bool");

extern "C" {static PyObject *meth_QsciLexerPOV_readProperties(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerPOV_readProperties(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QSettings * a0;
        const QString * a1;
        int a1State = 0;
        QsciLexerPOV *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ9J1", &sipSelf, sipType_QsciLexerPOV, &sipCpp, sipType_QSettings, &a0, sipType_QString,&a1, &a1State))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = (sipSelfWasArg ? sipCpp->QsciLexerPOV::readProperties(*a0,*a1) : sipCpp->readProperties(*a0,*a1));
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast<QString *>(a1),sipType_QString,a1State);

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerPOV, sipName_readProperties, doc_QsciLexerPOV_readProperties);

    return NULL;
}


PyDoc_STRVAR(doc_QsciLexerPOV_writeProperties, "QsciLexerPOV.writeProperties(QSettings, QString) -> bool");

extern "C" {static PyObject *meth_QsciLexerPOV_writeProperties(PyObject *, PyObject *);}
static PyObject *meth_QsciLexerPOV_writeProperties(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QSettings * a0;
        const QString * a1;
        int a1State = 0;
        QsciLexerPOV *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "pJ9J1", &sipSelf, sipType_QsciLexerPOV, &sipCpp, sipType_QSettings, &a0, sipType_QString,&a1, &a1State))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = (sipSelfWasArg ? sipCpp->QsciLexerPOV::writeProperties(*a0,*a1) : sipCpp->writeProperties(*a0,*a1));
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast<QString *>(a1),sipType_QString,a1State);

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QsciLexerPOV, sipName_writeProperties, doc_QsciLexerPOV_writeProperties);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_QsciLexerPOV(void *, const sipTypeDef *);}
static void *cast_QsciLexerPOV(void *ptr, const sipTypeDef *targetType)
{
    void *res;

    if (targetType == sipType_QsciLexerPOV)
        return ptr;

    if ((res = ((const sipClassTypeDef *)sipType_QsciLexer)->ctd_cast((QsciLexer *)(QsciLexerPOV *)ptr,targetType)) != NULL)
        return res;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QsciLexerPOV(void *, int);}
static void release_QsciLexerPOV(void *sipCppV,int)
{
    Py_BEGIN_ALLOW_THREADS

    QsciLexerPOV *sipCpp = reinterpret_cast<QsciLexerPOV *>(sipCppV);

    if (QThread::currentThread() == sipCpp->thread())
        delete sipCpp;
    else
        sipCpp->deleteLater();

    Py_END_ALLOW_THREADS
}


extern "C" {static void dealloc_QsciLexerPOV(sipSimpleWrapper *);}
static void dealloc_QsciLexerPOV(sipSimpleWrapper *sipSelf)
{
    if (sipIsDerived(sipSelf))
        reinterpret_cast<sipQsciLexerPOV *>(sipGetAddress(sipSelf))->sipPySelf = NULL;

    if (sipIsPyOwned(sipSelf))
    {
        release_QsciLexerPOV(sipGetAddress(sipSelf),sipSelf->flags);
    }
}


extern "C" {static void *init_QsciLexerPOV(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_QsciLexerPOV(sipSimpleWrapper *sipSelf, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **sipOwner, PyObject **sipParseErr)
{
    sipQsciLexerPOV *sipCpp = 0;

    {
        QObject * a0 = 0;

        static const char *sipKwdList[] = {
            sipName_parent,
        };

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, sipKwdList, sipUnused, "|JH", sipType_QObject, &a0, sipOwner))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new sipQsciLexerPOV(a0);
            Py_END_ALLOW_THREADS

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    return NULL;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QsciLexerPOV[] = {{7, 255, 1}};


static PyMethodDef methods_QsciLexerPOV[] = {
    {SIP_MLNAME_CAST(sipName_defaultColor), meth_QsciLexerPOV_defaultColor, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerPOV_defaultColor)},
    {SIP_MLNAME_CAST(sipName_defaultEolFill), meth_QsciLexerPOV_defaultEolFill, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerPOV_defaultEolFill)},
    {SIP_MLNAME_CAST(sipName_defaultFont), meth_QsciLexerPOV_defaultFont, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerPOV_defaultFont)},
    {SIP_MLNAME_CAST(sipName_defaultPaper), meth_QsciLexerPOV_defaultPaper, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerPOV_defaultPaper)},
    {SIP_MLNAME_CAST(sipName_description), meth_QsciLexerPOV_description, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerPOV_description)},
    {SIP_MLNAME_CAST(sipName_foldComments), meth_QsciLexerPOV_foldComments, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerPOV_foldComments)},
    {SIP_MLNAME_CAST(sipName_foldCompact), meth_QsciLexerPOV_foldCompact, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerPOV_foldCompact)},
    {SIP_MLNAME_CAST(sipName_foldDirectives), meth_QsciLexerPOV_foldDirectives, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerPOV_foldDirectives)},
    {SIP_MLNAME_CAST(sipName_keywords), meth_QsciLexerPOV_keywords, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerPOV_keywords)},
    {SIP_MLNAME_CAST(sipName_language), meth_QsciLexerPOV_language, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerPOV_language)},
    {SIP_MLNAME_CAST(sipName_lexer), meth_QsciLexerPOV_lexer, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerPOV_lexer)},
    {SIP_MLNAME_CAST(sipName_readProperties), meth_QsciLexerPOV_readProperties, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerPOV_readProperties)},
    {SIP_MLNAME_CAST(sipName_refreshProperties), meth_QsciLexerPOV_refreshProperties, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerPOV_refreshProperties)},
    {SIP_MLNAME_CAST(sipName_setFoldComments), meth_QsciLexerPOV_setFoldComments, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerPOV_setFoldComments)},
    {SIP_MLNAME_CAST(sipName_setFoldCompact), meth_QsciLexerPOV_setFoldCompact, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerPOV_setFoldCompact)},
    {SIP_MLNAME_CAST(sipName_setFoldDirectives), meth_QsciLexerPOV_setFoldDirectives, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerPOV_setFoldDirectives)},
    {SIP_MLNAME_CAST(sipName_writeProperties), meth_QsciLexerPOV_writeProperties, METH_VARARGS, SIP_MLDOC_CAST(doc_QsciLexerPOV_writeProperties)}
};

static sipEnumMemberDef enummembers_QsciLexerPOV[] = {
    {sipName_BadDirective, QsciLexerPOV::BadDirective, -1},
    {sipName_Comment, QsciLexerPOV::Comment, -1},
    {sipName_CommentLine, QsciLexerPOV::CommentLine, -1},
    {sipName_Default, QsciLexerPOV::Default, -1},
    {sipName_Directive, QsciLexerPOV::Directive, -1},
    {sipName_Identifier, QsciLexerPOV::Identifier, -1},
    {sipName_KeywordSet6, QsciLexerPOV::KeywordSet6, -1},
    {sipName_KeywordSet7, QsciLexerPOV::KeywordSet7, -1},
    {sipName_KeywordSet8, QsciLexerPOV::KeywordSet8, -1},
    {sipName_Number, QsciLexerPOV::Number, -1},
    {sipName_ObjectsCSGAppearance, QsciLexerPOV::ObjectsCSGAppearance, -1},
    {sipName_Operator, QsciLexerPOV::Operator, -1},
    {sipName_PredefinedFunctions, QsciLexerPOV::PredefinedFunctions, -1},
    {sipName_PredefinedIdentifiers, QsciLexerPOV::PredefinedIdentifiers, -1},
    {sipName_String, QsciLexerPOV::String, -1},
    {sipName_TypesModifiersItems, QsciLexerPOV::TypesModifiersItems, -1},
    {sipName_UnclosedString, QsciLexerPOV::UnclosedString, -1},
};

PyDoc_STRVAR(doc_QsciLexerPOV, "\1QsciLexerPOV(QObject parent=None)");


pyqt4ClassTypeDef sipTypeDef_Qsci_QsciLexerPOV = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_SCC|SIP_TYPE_CLASS,
        sipNameNr_QsciLexerPOV,
        {0}
    },
    {
        sipNameNr_QsciLexerPOV,
        {0, 0, 1},
        17, methods_QsciLexerPOV,
        17, enummembers_QsciLexerPOV,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    doc_QsciLexerPOV,
    -1,
    -1,
    supers_QsciLexerPOV,
    0,
    init_QsciLexerPOV,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QsciLexerPOV,
    0,
    0,
    0,
    release_QsciLexerPOV,
    cast_QsciLexerPOV,
    0,
    0,
    0
},
    &QsciLexerPOV::staticMetaObject,
    0,
    0
};
