#!/usr/bin/env python
import sys
sys.path.append("src/core/")
# import the core module
import core

try:
	# pull update set from the core libraries
	core.update_set()

# except keyboard interrupts
except KeyboardInterrupt:
	print "\n[!] Control-C detected. Exiting updating SET."

# handle all other errors
except Exception, e: print "\n[!] Something went wrong.. Printing the error: " + e

